import test from 'node:test';
import assert from 'node:assert/strict';
import { compareHealth, compareTerm, normalizeEnrollment, newOption, newPerson, EMPTY_ENROLLMENT } from '../lib/enrollment.ts';
import { normalizePlan, DEFAULT_PLAN } from '../lib/planner.ts';
import { baselineSnapshot } from '../lib/scenarios.ts';

function fixture(costs=[10000]) {
  const e={...structuredClone(EMPTY_ENROLLMENT),startMonth:'2026-01',processingMonths:0,dueMonths:0,reimbursementMonths:0,people:costs.map((n,i)=>({...newPerson(`p${i}`),hsaEligible:'yes',annualMedical:n,timing:'once',month:1}))};
  const p={...newOption('a'),premium:100,payPeriods:12,individualDeductible:1000,familyDeductible:3000,individualMax:3000,familyMax:6000,coinsurance:20};e.options=[p];return {e,p};
}
const close=(a,b)=>assert.ok(Math.abs(a-b)<0.00001,`${a} != ${b}`);
test('individual deductible, coinsurance and annual premium are distinct',()=>{const {e,p}=fixture();const r=compareHealth(e,p);assert.deepEqual(r.issues,[]);close(r.medical,2800);close(r.total,4000);close(r.claims[0].deductible,1000);});
test('concentrated family claims stop at individual OOP even under an aggregate deductible',()=>{const {e,p}=fixture([50000,0]);p.deductibleMode='aggregate';p.familyDeductible=7000;const r=compareHealth(e,p);close(r.medical,3000);close(r.people[0].oop,3000);close(r.people[1].oop,0);close(r.claims[0].deductible,3000);});
test('embedded and aggregate family deductibles produce different supported costs',()=>{const {e,p}=fixture([2000,0]);close(compareHealth(e,p).medical,1200);p.deductibleMode='aggregate';close(compareHealth(e,p).medical,2000);});
test('family OOP caps total payments and a later family member gets remaining protection',()=>{const {e,p}=fixture([50000,50000,50000]);p.familyMax=4500;const r=compareHealth(e,p);close(r.medical,4500);assert.deepEqual(r.people.map(x=>x.oop),[3000,1500,0]);});
test('family deductible accumulates across people and then coinsurance begins',()=>{const {e,p}=fixture([2000,2000,2000]);p.familyDeductible=1500;const r=compareHealth(e,p);close(r.medical,2400);assert.deepEqual(r.people.map(x=>x.medical),[1200,800,400]);});
function prescription(e,p,patch={},rule={}){e.people[0].care=[{id:'rx',kind:'prescription',label:'Fictional Rx',allowed:1000,count:2,timing:'spread',month:null,...patch}];p.rules.rx={coverage:'covered',deductible:'shared',payment:'coinsurance',amount:20,countsOop:'yes',...rule};}
test('shared Rx deductible and combined OOP credit reconcile with medical',()=>{const {e,p}=fixture([500]);prescription(e,p);const r=compareHealth(e,p);close(r.medical,500);close(r.prescriptions,800);close(r.people[0].oop,1300);});
test('separate Rx deductible and optional sublimit still feed combined OOP maximum',()=>{const {e,p}=fixture([0]);prescription(e,p,{}, {deductible:'separate'});p.rxIndividualDeductible=500;p.rxIndividualMax=600;const r=compareHealth(e,p);assert.deepEqual(r.issues,[]);close(r.prescriptions,600);close(r.people[0].oop,600);});
test('deductible-exempt copays count toward OOP without using the deductible',()=>{const {e,p}=fixture([0]);prescription(e,p,{allowed:20,count:12},{deductible:'exempt',payment:'copay',amount:40});const r=compareHealth(e,p);close(r.prescriptions,240);close(r.people[0].oop,240);close(r.claims.reduce((n,c)=>n+c.deductible,0),0);});
test('excluded Rx and covered costs outside OOP remain payable after the cap',()=>{const {e,p}=fixture([50000]);prescription(e,p,{}, {countsOop:'no'});const r=compareHealth(e,p);close(r.medical,3000);close(r.prescriptions,400);close(r.people[0].oop,3000);p.rules.rx.coverage='excluded';const excluded=compareHealth(e,p);close(excluded.excluded,2000);close(excluded.people[0].oop,3000);});
test('unknown formulary and OOP treatment block a complete comparison',()=>{const {e,p}=fixture([0]);prescription(e,p);p.rules.rx.countsOop='unknown';assert.ok(compareHealth(e,p).issues.some(x=>x.includes('combined out-of-pocket')));p.rules.rx.coverage='unknown';assert.ok(compareHealth(e,p).issues.some(x=>x.includes('confirm coverage')));});
test('confirmed preventive care is free, with no deductible or OOP credit',()=>{const {e,p}=fixture([0]);prescription(e,p,{kind:'preventive'},{coverage:'covered',countsOop:'unknown',amount:null});const r=compareHealth(e,p);assert.deepEqual(r.issues,[]);close(r.total,1200);close(r.people[0].oop,0);});
test('EOB and provider billing delays do not change service-year costs; pharmacy is immediate',()=>{const {e,p}=fixture([10000]);e.people[0].month=12;e.processingMonths=2;e.dueMonths=1;prescription(e,p,{count:1,timing:'once',month:12});const r=compareHealth(e,p);assert.equal(r.timeline.length,15);assert.equal(r.timeline[14].month,'2027-03');close(r.timeline[14].bills,2800);close(r.timeline[11].bills,200);close(r.timeline[13].eob,3000);close(r.timeline.reduce((n,m)=>n+m.bills,0),r.medical+r.prescriptions);});
test('HSA deposits, reimbursements, remaining assets and tax benefits do not double count',()=>{const {e,p}=fixture([1000]);p.hsa=true;p.eligibilityConfirmed=true;p.contributionLimit=4400;p.employerHsa=1200;p.ownHsa=1200;p.openingHsa=0;p.taxRate=25;e.qualifiedConfirmed=true;const r=compareHealth(e,p);assert.deepEqual(r.issues,[]);close(r.netCost,700);close(r.endingHsa,1400);close(r.taxSavings,300);close(r.timeline.reduce((n,m)=>n+m.reimbursement,0),1000);close(r.timeline.reduce((n,m)=>n+m.outsideCash,0),2400);close(r.peakBridge,800);p.employerTiming='upfront';close(compareHealth(e,p).peakBridge,0);});
test('reimbursement lag can extend past year end without inventing future contributions',()=>{const {e,p}=fixture([1000]);e.people[0].month=12;e.processingMonths=1;e.dueMonths=1;e.reimbursementMonths=2;e.qualifiedConfirmed=true;Object.assign(p,{hsa:true,eligibilityConfirmed:true,contributionLimit:4400,employerHsa:1200,ownHsa:0,openingHsa:0,taxRate:0});const r=compareHealth(e,p);close(r.timeline[13].bills,1000);close(r.timeline[15].reimbursement,1000);close(r.endingHsa,200);close(r.timeline.slice(12).reduce((s,m)=>s+m.employerContribution+m.ownContribution+m.premium,0),0);});
test('HSA annual allowance and reimbursement qualification must be confirmed',()=>{const {e,p}=fixture([0]);Object.assign(p,{hsa:true,eligibilityConfirmed:false,contributionLimit:4400,employerHsa:4000,ownHsa:1000,openingHsa:0,taxRate:25});const r=compareHealth(e,p);assert.ok(r.issues.some(x=>x.includes('eligibility')));assert.ok(r.issues.some(x=>x.includes('exceed')));assert.ok(r.issues.some(x=>x.includes('qualify')));});
test('existing HSA can reimburse qualified care without new contribution eligibility',()=>{const {e,p}=fixture([1000]);e.qualifiedConfirmed=true;Object.assign(p,{hsa:true,eligibilityConfirmed:false,contributionLimit:0,employerHsa:0,ownHsa:0,openingHsa:1500,taxRate:0});const r=compareHealth(e,p);assert.deepEqual(r.issues,[]);close(r.endingHsa,500);close(r.taxSavings,0);});
test('historical personal out-of-pocket amount cannot masquerade as allowed charges',()=>{const {e,p}=fixture();e.people[0].basis='priorOop';assert.ok(compareHealth(e,p).issues.some(x=>x.includes('not an allowed-charge')));});
test('medical stress preserves prescription frequency and excluded prices',()=>{const {e,p}=fixture([1000]);prescription(e,p,{allowed:40,count:12},{deductible:'exempt',payment:'copay',amount:10});close(compareHealth(e,p,2).prescriptions,compareHealth(e,p,1).prescriptions);assert.ok(compareHealth(e,p,2).medical>compareHealth(e,p,1).medical);});
test('new enrollment inputs are blank and imported data are bounded',()=>{const blank=normalizeEnrollment(EMPTY_ENROLLMENT);assert.equal(blank.processingMonths,null);assert.deepEqual(blank.people,[]);assert.equal(newOption('p').premium,null);assert.equal(newPerson('x').annualMedical,null);const {e,p}=fixture();e.people[0].care=[{id:'rx',kind:'prescription',label:'',allowed:20,count:12,timing:'spread',month:null,payAtService:false}];p.coinsurance=Infinity;p.payPeriods=-1;e.processingMonths=99;e.people[0].annualMedical='5000';const safe=normalizeEnrollment(e);assert.equal(safe.options[0].coinsurance,null);assert.equal(safe.options[0].payPeriods,null);assert.equal(safe.people[0].annualMedical,null);assert.equal(safe.processingMonths,null);assert.equal(safe.people[0].care[0].payAtService,false);});
test('comparison edits survive JSON round trip without altering retirement scenario baselines',()=>{const {e}=fixture();const plan=normalizePlan(structuredClone(DEFAULT_PLAN)),before=baselineSnapshot(plan);plan.enrollment=e;const imported=normalizePlan(JSON.parse(JSON.stringify(plan)));assert.equal(imported.enrollment.options[0].premium,100);assert.equal(baselineSnapshot(imported),before);});
test('term quotes stop cost comparison at guarantee or employment boundary',()=>{const q={id:'q',label:'Fictional Term',ownership:'individual',coverage:500000,premium:400,years:15,guaranteedYears:15,portable:'unknown'};close(compareTerm(q,3).knownPremiums,6000);close(compareTerm({...q,ownership:'employer'},3).knownPremiums,1200);close(compareTerm({...q,guaranteedYears:1},3).knownPremiums,400);assert.ok(compareTerm({...q,ownership:'employer'},null).issues.length>0);});
test('premium tax benefits change annual economics without funding monthly bills',()=>{const {e,p}=fixture([0]);p.premiumTaxRate=25;const r=compareHealth(e,p);close(r.premiumTaxSavings,300);close(r.netCost,900);close(r.timeline.reduce((n,m)=>n+m.outsideCash,0),1200);});
test('health-family membership is separate from per-person HSA reimbursement eligibility',()=>{const {e,p}=fixture([1000,1000]);e.qualifiedConfirmed=true;Object.assign(p,{hsa:true,eligibilityConfirmed:true,contributionLimit:8750,employerHsa:0,ownHsa:0,openingHsa:5000,taxRate:0});e.people[1].hsaEligible='no';const r=compareHealth(e,p);assert.deepEqual(r.issues,[]);close(r.medical,2000);close(r.endingHsa,4000);close(r.timeline.reduce((n,m)=>n+m.reimbursement,0),1000);e.people[1].hsaEligible='unknown';assert.ok(compareHealth(e,p).issues.some(x=>x.includes('Person 2: confirm eligibility')));});
test('an item can be excluded from HSA reimbursement without changing plan cost sharing',()=>{const {e,p}=fixture([0]);prescription(e,p,{hsaExcluded:true},{deductible:'exempt',payment:'copay',amount:20});e.qualifiedConfirmed=true;Object.assign(p,{hsa:true,contributionLimit:0,employerHsa:0,ownHsa:0,openingHsa:5000,taxRate:0});const r=compareHealth(e,p);close(r.prescriptions,40);close(r.endingHsa,5000);close(r.people[0].oop,40);});
test('plan-specific prescription prices retain the same fill schedule',()=>{const {e,p}=fixture([0]);prescription(e,p,{}, {deductible:'exempt',amount:20,allowedOverride:500});const r=compareHealth(e,p);close(r.prescriptions,200);assert.equal(r.claims.filter(c=>c.kind==='prescription').length,2);const normalized=normalizeEnrollment(e);close(normalized.options[0].rules.rx.allowedOverride,500);});
