"use client";
import { useState } from 'react';
import { Plus, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { BUDGET_CATEGORIES, FREQUENCIES, annualize, budgetTotals, retirementAmount, scheduledPayments, type BudgetData, type BudgetLine, type Frequency } from '@/lib/budget';
import { buildBudgetYear, payrollReconciliation, type BudgetHousehold } from '@/lib/budget-calendar';
import type { Account } from '@/lib/planner';

const money = (n: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(n);
export function Amount({ label, value, onChange, percent = false }: { label: string; value: number | null; onChange: (n: number | null) => void; percent?: boolean }) {
  return <label className="budget-field"><span>{label}</span><div className="input-affix"><span>{percent ? '%' : '$'}</span><Input aria-label={label} type="number" min={percent ? -100 : 0} step="any" value={value ?? ''} onFocus={e => e.currentTarget.select()} onChange={e => onChange(e.target.value === '' ? null : e.target.valueAsNumber)} /></div></label>;
}
function FrequencySelect({ value, onChange }: { value: Frequency; onChange: (v: Frequency) => void }) {
  return <label className="budget-field"><span>Frequency</span><select aria-label="Frequency" value={value} onChange={e => onChange(e.target.value as Frequency)}>{Object.entries(FREQUENCIES).map(([key, f]) => <option key={key} value={key}>{f.label}</option>)}</select></label>;
}
export function BudgetEditor({ budget, onChange, retirement = false, married, linkedAnnual, legacyAnnual, accounts, household }: { budget: BudgetData; onChange: (b: BudgetData) => void; retirement?: boolean; married: boolean; linkedAnnual: { housing: number; debt: number; health: number }; legacyAnnual: number; accounts: Account[]; household: BudgetHousehold }) {
  const [month, setMonth] = useState(0);
  const [showSchedule, setShowSchedule] = useState(false);
  const [undo, setUndo] = useState<BudgetData | null>(null);
  const year = new Date().getFullYear();
  const current = budgetTotals(budget);
  const future = budgetTotals(budget, true);
  const totals = retirement ? future : current;
  const linked = linkedAnnual.housing + linkedAnnual.debt + linkedAnnual.health;
  const savings = (budget.savings ?? []).reduce((n,s) => n + (annualize(s.amount,s.frequency) ?? 0),0);
  const groupFor = (l: BudgetLine) => budget.presentation === 'simple' ? (['annual','quarterly'].includes(l.frequency) ? 'Nonmonthly Costs' : l.flexibility === 'fixed' ? 'Fixed Commitments' : 'Flexible Costs') : l.category;
  const groups = [...new Set(budget.lines.map(groupFor))];
  const calendar = buildBudgetYear(budget, household, budget.timeline?.startYear ?? year, budget.timeline?.startYear ?? year, accounts.map(a=>a.id));
  const timeline = budget.timeline ?? { startYear:null, retirementMonthYou:'', retirementMonthPartner:'' };
  const updateLine = (id: string, patch: Partial<BudgetLine>) => onChange({ ...budget, reviewed: false, lines: budget.lines.map(l => l.id === id ? { ...l, ...patch } : l) });
  const addLine = (category: string) => onChange({ ...budget, reviewed: false, lines: [...budget.lines, { id: crypto.randomUUID(), name: '', category, amount: null, frequency: 'monthly', essential: false, owner: 'household', nextDueDate: '', endDate: '', retirement: { rule: retirement ? 'retirementOnly' : 'continue', amount: null, reason: '' } }] });
  const missingSchedule = budget.lines.filter(l => l.retirement.rule !== 'retirementOnly' && scheduledPayments(l.amount, l.frequency, l.nextDueDate, year, l.endDate) === null).length;
  return <div className="budget-flow">
    <div className="section-heading"><h1>{retirement ? 'Retirement Budget' : 'Current Budget'}</h1><p>{retirement ? 'Start with the life you know. Keep what fits, then change only what retirement changes.' : 'Start with your take-home pay and a few bills. You can refine the details whenever you are ready.'}</p></div>
    <div className="budget-metrics">
      <div><span>{retirement ? 'Current Everyday Costs' : 'Take-Home Pay'} / Month</span><strong>{money((retirement ? current.spending : current.takeHome) / 12)}</strong></div>
      <div><span>{retirement ? 'Retirement Everyday Costs' : 'Entered Costs Including Linked Items'} / Month</span><strong>{money((totals.spending + (retirement ? 0 : linked)) / 12)}</strong></div>
      <div><span>{retirement ? 'Everyday Cost Change' : 'Remaining After Planned Savings'} / Month</span><strong>{money((retirement ? future.spending - current.spending : current.margin - linked - savings) / 12)}</strong></div>
    </div>
    <p className="field-help">{totals.missing > 0 ? `${totals.missing} entries still need an amount. ` : ''}These totals cover entered items only. Monthly averages spread irregular bills across the year; they are not actual due-month spending.</p>
    <div className="budget-toolbar"><label className="budget-field"><span>Budget View</span><select aria-label="Budget View" value={budget.presentation ?? 'category'} onChange={e=>onChange({...budget,presentation:e.target.value as 'simple'|'category'})}><option value="simple">Simple: Fixed, Flexible & Nonmonthly</option><option value="category">By Category</option></select></label><p className="field-help">Both views use the same bills. Enter a category total as one row, or individual bills; do not enter both for the same costs.</p></div>
    <details className="panel budget-flow"><summary>Monthly Timeline & Retirement Dates</summary><p>Opening balances are as of January 1 of the selected year. An entered retirement month stops that person's pay and changes their assigned bills at the start of that month. Household bills change when both retire. Without a month, the age-based January convention applies.</p><div className="budget-fields"><label className="budget-field"><span>Opening-Balance Year</span><Input aria-label="Opening-Balance Year" type="number" min="2026" max="2100" value={timeline.startYear ?? ''} onChange={e=>onChange({...budget,timeline:{...timeline,startYear:e.target.value===''?null:+e.target.value}})} /></label><label className="budget-field"><span>Your Retirement Month</span><Input aria-label="Your Retirement Month" type="month" value={timeline.retirementMonthYou} onChange={e=>onChange({...budget,timeline:{...timeline,retirementMonthYou:e.target.value}})} /></label>{married&&<label className="budget-field"><span>Partner's Retirement Month</span><Input aria-label="Partner Retirement Month" type="month" value={timeline.retirementMonthPartner} onChange={e=>onChange({...budget,timeline:{...timeline,retirementMonthPartner:e.target.value}})} /></label>}</div></details>

    {!retirement && <section className="panel budget-flow"><h2>Take-Home Pay</h2><p>Start with the amount deposited after deductions. Pension and Social Security remain in Benefits. Add the optional payroll breakdown when you are ready to use the monthly tax projection.</p>
      {budget.pay.map(p => <div className="budget-card" key={p.id}><div className="budget-fields">
        <label className="budget-field"><span>Pay Description</span><Input value={p.name} onChange={e => onChange({ ...budget, pay: budget.pay.map(q => q.id === p.id ? { ...q, name: e.target.value } : q) })} /></label>
        <Amount label="Take-Home per Payment" value={p.amount} onChange={amount => onChange({ ...budget, pay: budget.pay.map(q => q.id === p.id ? { ...q, amount } : q) })} />
        <FrequencySelect value={p.frequency} onChange={frequency => onChange({ ...budget, pay: budget.pay.map(q => q.id === p.id ? { ...q, frequency } : q) })} />
        <label className="budget-field"><span>Whose Pay?</span><select aria-label="Whose Pay?" value={p.owner} onChange={e => onChange({ ...budget, pay: budget.pay.map(q => q.id === p.id ? { ...q, owner: e.target.value as 'you' | 'partner' } : q) })}><option value="you">You</option>{married && <option value="partner">Partner</option>}</select></label>
        <label className="budget-field"><span>Next Pay Date (Optional)</span><Input type="date" value={p.nextPayDate} onChange={e => onChange({ ...budget, pay: budget.pay.map(q => q.id === p.id ? { ...q, nextPayDate: e.target.value } : q) })} /></label>
      </div><details><summary>Payroll Breakdown & Savings</summary><p>All amounts are per paycheck. Income-tax withholding excludes Social Security/Medicare payroll taxes; put those and insurance in Other Deductions. Taxable wages are the income-tax wage amount after eligible pretax deductions. Enter zero explicitly where appropriate.</p><div className="budget-fields">{(['gross','taxableWages','incomeTaxWithheld','otherDeductions','employeeSavings','employerSavings'] as const).map(key=><Amount key={key} label={{gross:'Gross Pay',taxableWages:'Taxable Wages',incomeTaxWithheld:'Income-Tax Withheld',otherDeductions:'Other Payroll Deductions',employeeSavings:'Employee Payroll Savings',employerSavings:'Employer Contributions'}[key]} value={p.payroll?.[key]??null} onChange={value=>onChange({...budget,pay:budget.pay.map(q=>q.id===p.id?{...q,payroll:{gross:null,taxableWages:null,incomeTaxWithheld:null,otherDeductions:null,employeeSavings:null,employerSavings:null,accountId:'',...q.payroll,[key]:value}}:q)})} />)}<label className="budget-field"><span>Payroll Savings Account</span><select aria-label="Payroll Savings Account" value={p.payroll?.accountId??''} onChange={e=>onChange({...budget,pay:budget.pay.map(q=>q.id===p.id?{...q,payroll:{gross:null,taxableWages:null,incomeTaxWithheld:null,otherDeductions:null,employeeSavings:null,employerSavings:null,...q.payroll,accountId:e.target.value}}:q)})}><option value="">Select Account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name||a.kind}</option>)}</select></label></div><p className="field-help">{payrollReconciliation(p,accounts.map(a=>a.id)).reason} Split pay into separate reconciled entries if savings go to several accounts. Contribution eligibility and limits require your confirmation; no payroll-tax estimator is implied.</p></details><Button variant="ghost" aria-label="Remove Pay Entry" onClick={() => onChange({ ...budget, pay: budget.pay.filter(q => q.id !== p.id) })}><Trash2 /> Remove</Button></div>)}
      <Button variant="outline" onClick={() => onChange({ ...budget, pay: [...budget.pay, { id: crypto.randomUUID(), name: '', owner: 'you', amount: null, frequency: 'monthly', nextPayDate: '' }] })}><Plus /> Add Take-Home Pay</Button>
    </section>}

    <section className="panel budget-flow"><h2>{retirement ? 'What Changes?' : 'Everyday Bills'}</h2><p>Housing property tax and insurance, debt payments, and entered healthcare are linked below. Add other bills here to avoid counting those costs twice. Classification starts unconfirmed: mark the bills you consider essential.</p>
      {groups.map(group=><details className="budget-group" key={group} open><summary><span>{group}</span><strong>{money(budget.lines.filter(l=>groupFor(l)===group).reduce((n,l)=>n+(annualize(retirement?retirementAmount(l):l.retirement.rule==='retirementOnly'?0:l.amount,l.frequency)??0)/12,0))} / month</strong></summary>{budget.lines.filter(l=>groupFor(l)===group).map(l => <div className="budget-card" key={l.id}>
        <div className="budget-comparison"><strong>{l.name||l.category}</strong><span>Today <b>{l.amount===null?'Not Entered':money((annualize(l.retirement.rule==='retirementOnly'?0:l.amount,l.frequency)??0)/12)}</b></span><span>Retirement <b>{retirementAmount(l)===null?'Not Entered':money((annualize(retirementAmount(l),l.frequency)??0)/12)}</b></span></div>
        <div className="budget-fields">
          <label className="budget-field"><span>Description</span><Input value={l.name} onChange={e => updateLine(l.id, { name: e.target.value })} /></label>
          <label className="budget-field"><span>Category</span><select aria-label="Category" value={l.category} onChange={e => updateLine(l.id, { category: e.target.value })}>{BUDGET_CATEGORIES.map(c => <option key={c}>{c}</option>)}</select></label>
          {l.retirement.rule !== 'retirementOnly' && !retirement && <Amount label="Current Amount" value={l.amount} onChange={amount => updateLine(l.id, { amount })} />}
          <FrequencySelect value={l.frequency} onChange={frequency => updateLine(l.id, { frequency })} />
          <label className="budget-check"><input type="checkbox" checked={l.essential} onChange={e => updateLine(l.id, { essential: e.target.checked })} /> Essential Cost</label>
        </div>
        {retirement ? <>
          <div className="budget-fields"><label className="budget-field"><span>In Retirement</span><select aria-label="In Retirement" value={l.retirement.rule} onChange={e => updateLine(l.id, { retirement: { ...l.retirement, rule: e.target.value as BudgetLine['retirement']['rule'] } })}><option value="continue">Continue Current Amount</option><option value="stop">Stop</option><option value="replace">Replace Amount</option><option value="percent">Change by Percentage</option><option value="retirementOnly">New Retirement Cost</option></select></label>
          {['replace', 'percent', 'retirementOnly'].includes(l.retirement.rule) && <Amount label={l.retirement.rule === 'percent' ? 'Change (− for Less)' : 'Retirement Amount'} percent={l.retirement.rule === 'percent'} value={l.retirement.amount} onChange={amount => updateLine(l.id, { retirement: { ...l.retirement, amount } })} />}
          <label className="budget-field"><span>Reason (Optional)</span><Input value={l.retirement.reason} onChange={e => updateLine(l.id, { retirement: { ...l.retirement, reason: e.target.value } })} /></label></div>
          <p className="field-help">Current: {l.amount === null ? 'Not Entered' : money(annualize(l.amount, l.frequency)! / 12)} / month → Retirement: {retirementAmount(l) === null ? 'Not Entered' : money(annualize(retirementAmount(l), l.frequency)! / 12)} / month. {l.retirement.rule === 'continue' ? 'Linked: editing the current amount updates retirement too.' : 'Explicit retirement choice preserved when the current amount changes.'}</p>
        </> : <details><summary>Bill Timing</summary><div className="budget-fields"><label className="budget-field"><span>Next Due Date</span><Input type="date" value={l.nextDueDate} onChange={e => updateLine(l.id, { nextDueDate: e.target.value })} /></label><label className="budget-field"><span>Final Due Date (Optional)</span><Input type="date" value={l.endDate} onChange={e => updateLine(l.id, { endDate: e.target.value })} /></label></div><p className="field-help">Twice-monthly scheduling uses the 15th and last day. Weekly dates may yield 53 payments; biweekly may yield 27 in some years. The monthly engine uses dates where entered, otherwise explicitly labeled averages.</p></details>}
        <details><summary>Classification & Dated Changes</summary><div className="budget-fields"><label className="budget-field"><span>Adjustability</span><select value={l.flexibility??'flexible'} onChange={e=>updateLine(l.id,{flexibility:e.target.value as 'fixed'|'flexible'})}><option value="fixed">Fixed Commitment</option><option value="flexible">Flexible Cost</option></select></label><label className="budget-field"><span>Retirement Trigger</span><select value={l.owner} onChange={e=>updateLine(l.id,{owner:e.target.value as BudgetLine['owner']})}><option value="household">Full Household Retirement</option><option value="you">Your Retirement</option>{married&&<option value="partner">Partner's Retirement</option>}</select></label></div><p className="field-help">Flexibility and essential priority are separate. Dated amounts below use this row's payment frequency and take precedence over its usual retirement rule.</p>{(budget.overrides??[]).filter(o=>o.lineId===l.id).map(o=><div className="budget-fields" key={o.id}><label className="budget-field"><span>From Month</span><Input type="month" value={o.fromMonth} onChange={e=>onChange({...budget,overrides:budget.overrides!.map(v=>v.id===o.id?{...v,fromMonth:e.target.value}:v)})} /></label><label className="budget-field"><span>Through Month (Blank = Onward)</span><Input type="month" value={o.throughMonth} onChange={e=>onChange({...budget,overrides:budget.overrides!.map(v=>v.id===o.id?{...v,throughMonth:e.target.value}:v)})} /></label><Amount label="Dated Amount per Payment" value={o.amount} onChange={amount=>onChange({...budget,overrides:budget.overrides!.map(v=>v.id===o.id?{...v,amount}:v)})} /><Button variant="ghost" onClick={()=>{setUndo(structuredClone(budget));onChange({...budget,overrides:budget.overrides!.filter(v=>v.id!==o.id)});}}>Remove Dated Change</Button></div>)}<Button variant="outline" onClick={()=>{setUndo(structuredClone(budget));onChange({...budget,overrides:[...(budget.overrides??[]),{id:crypto.randomUUID(),lineId:l.id,fromMonth:'',throughMonth:'',amount:null}]});}}>Add Dated Change</Button>{undo&&<Button variant="ghost" onClick={()=>{onChange(undo);setUndo(null);}}>Undo Dated Change</Button>}</details>
        <Button variant="ghost" aria-label={`Remove ${l.name || l.category} Cost`} onClick={() => onChange({ ...budget, reviewed: false, lines: budget.lines.filter(q => q.id !== l.id),overrides:budget.overrides?.filter(o=>o.lineId!==l.id) })}><Trash2 /> Remove Cost</Button>
      </div>)}</details>)}
      <div className="budget-actions">{BUDGET_CATEGORIES.map(c => <Button key={c} variant="outline" onClick={() => addLine(c)}><Plus /> {c}</Button>)}</div>
    </section>
    {!retirement&&<section className="panel budget-flow"><h2>Savings from Take-Home Pay</h2><p>These are account transfers after payday, separate from consumption and payroll savings. The monthly engine caps transfers at available cash and reports unmet savings. Legacy annual account contributions are not added again.</p>{(budget.savings??[]).map(s=><div className="budget-fields" key={s.id}><Amount label="Savings per Month" value={s.amount} onChange={amount=>onChange({...budget,savings:budget.savings!.map(v=>v.id===s.id?{...v,amount,frequency:'monthly'}:v)})} /><label className="budget-field"><span>Destination Account</span><select aria-label="Destination Account" value={s.accountId} onChange={e=>onChange({...budget,savings:budget.savings!.map(v=>v.id===s.id?{...v,accountId:e.target.value}:v)})}><option value="">Select Account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name||a.kind}</option>)}</select></label><Button variant="ghost" onClick={()=>onChange({...budget,savings:budget.savings!.filter(v=>v.id!==s.id)})}>Remove Savings Transfer</Button></div>)}<Button variant="outline" onClick={()=>onChange({...budget,savings:[...(budget.savings??[]),{id:crypto.randomUUID(),name:'',accountId:'',amount:null,frequency:'monthly',owner:'household'}]})}>Add Savings Transfer</Button></section>}
    <details className="panel budget-flow"><summary>By the Month: Planned Budget</summary><p>Uses retirement dates and scoped changes. This table excludes linked housing, debt, benefits, tax settlement and investment funding; the complete ledger is in Scenario Laboratory. Scheduled is not observed spending.</p><div className="budget-calendar-grid">{calendar.map(m=><div className="budget-calendar-row" key={m.month}><span>{m.month}<small>{m.averageSchedules?'Includes Monthly Averages':'Scheduled Dates'}</small></span><span>Pay {money(m.takeHome)}<br/>Bills {money(m.spending)}<br/>Savings Target {money(m.requestedSavings)}</span></div>)}</div></details>

    <section className="panel budget-flow"><h2>Linked Costs</h2><p>These are read from their existing sections, never copied into your everyday bills. They stay separate in retirement projections.</p><dl className="budget-metrics"><div><dt>Home Taxes & Insurance / Month</dt><dd>{money(linkedAnnual.housing / 12)}</dd></div><div><dt>First-Year Debt Payments / Month</dt><dd>{money(linkedAnnual.debt / 12)}</dd></div><div><dt>Entered Healthcare / Month</dt><dd>{money(linkedAnnual.health / 12)}</dd></div></dl><p className="field-help">Timed expenses, payroll savings, pension/benefit withholding, and other unentered obligations are not included in the current margin above. Debt amounts assume principal and interest exclude escrow.</p></section>

    {retirement ? <section className="panel budget-flow"><h2>Use This in the Projection</h2><p>Choose either the existing aggregate retirement baseline ({money(legacyAnnual)} / year) or this worksheet ({money(future.spending)} / year). They are never added together. Worksheet amounts are in today's dollars; inflation is applied in the projection.</p><label className="budget-field"><span>Retirement Spending Source</span><select aria-label="Retirement Spending Source" value={budget.retirementSpendingSource} onChange={e => onChange({ ...budget, retirementSpendingSource: e.target.value as BudgetData['retirementSpendingSource'] })}><option value="legacy">Existing Aggregate Baseline</option><option value="worksheet">Linked Budget Worksheet</option></select></label><label className="budget-check"><input type="checkbox" checked={budget.reviewed} onChange={e => onChange({ ...budget, reviewed: e.target.checked })} /> I have reviewed the everyday costs and the separately linked costs.</label><p className="field-help">Scenario Laboratory uses the monthly budget, owner transitions and reconciled payroll. The legacy annual Plan Summary remains a separate estimate until the monthly engine is selected there.</p></section> : <section className="panel budget-flow"><h2>Bill Calendar</h2><Button variant="outline" onClick={() => setShowSchedule(!showSchedule)}>{showSchedule ? 'Hide' : 'Show'} Scheduled Payments</Button>{showSchedule && <><label className="budget-field"><span>Month in {year}</span><select aria-label="Calendar Month" value={month} onChange={e => setMonth(+e.target.value)}>{Array.from({ length: 12 }, (_, m) => <option key={m} value={m}>{new Date(year, m).toLocaleString('en-US', { month: 'long' })}</option>)}</select></label><p>{missingSchedule ? `${missingSchedule} costs have no complete due-date schedule; they are excluded below.` : 'All entered everyday costs have schedules.'} This calendar covers everyday bills only; linked costs remain separate.</p>{budget.lines.filter(l => l.retirement.rule !== 'retirementOnly').map(l => { const schedule = scheduledPayments(l.amount, l.frequency, l.nextDueDate, year, l.endDate); return <div className="budget-calendar-row" key={l.id}><span>{l.name || l.category}</span><strong>{schedule === null ? 'Date / Amount Needed' : money(schedule[month])}</strong></div>; })}</>}</section>}
  </div>;
}
