"use client";
import { FormGrid } from '@/components/ui/planner-layout';
import { Amount } from '@/components/budget-editor';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { budgetAllocation, FREQUENCIES, type BudgetLine } from '@/lib/budget';
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
export function BudgetBreakdown({line,retirement,onChange}:{line:BudgetLine;retirement:boolean;onChange:(line:BudgetLine)=>void}){
 const allocations=line.allocations??[],result=budgetAllocation(line,retirement);
 const update=(id:string,patch:Partial<typeof allocations[number]>)=>onChange({...line,allocations:allocations.map(a=>a.id===id?{...a,...patch}:a)});
 return <details><summary>Break Down This Amount</summary><p className="field-help">Start with one total, then explain it with individual bills. These details are included inside the total and are never added again. All amounts use this row's {FREQUENCIES[line.frequency].label.toLowerCase()} frequency and its essential/discretionary classification. Keep separately linked housing, debt and health costs out of this total.</p><p>{result.total===null?'Enter the envelope total first.':`Total ${money(result.total)} · Allocated ${money(result.allocated)} · ${result.overallocated?'Overallocated':'Unallocated'} ${money(Math.abs(result.remaining!))}`}{result.missing>0?` · ${result.missing} details await amounts; their share remains inside the envelope.`:''}</p>{allocations.map(a=><FormGrid as="div" className="budget-fields" key={a.id}><label className="budget-field"><span>Bill Label</span><Input aria-label="Allocation Label" value={a.name} onChange={e=>update(a.id,{name:e.target.value})}/></label>{retirement?<><label className="budget-field"><span>Allocation in Retirement</span><select aria-label="Allocation in Retirement" value={a.retirement.rule} onChange={e=>update(a.id,{retirement:{...a.retirement,rule:e.target.value as typeof a.retirement.rule}})}><option value="continue">Use Current Allocation</option><option value="stop">Stops</option><option value="replace">Different Allocation</option></select></label>{a.retirement.rule==='replace'&&<Amount label="Retirement Allocation" value={a.retirement.amount} onChange={amount=>update(a.id,{retirement:{...a.retirement,amount}})}/>}</>:<Amount label="Current Allocation" value={a.amount} onChange={amount=>update(a.id,{amount})}/>}<Button variant="ghost" onClick={()=>onChange({...line,allocations:allocations.filter(v=>v.id!==a.id)})}>Remove Allocation</Button></FormGrid>)}<Button variant="outline" onClick={()=>onChange({...line,allocations:[...allocations,{id:crypto.randomUUID(),name:'',amount:null,retirement:{rule:'continue',amount:null}}]})}>Add Bill Allocation</Button>{result.overallocated&&<p role="alert">Increase the total or reduce its allocations. Projection comparisons pause until these amounts reconcile.</p>}</details>;
}
