"use client";
import { FormGrid } from '@/components/ui/planner-layout';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import type { BudgetLine } from '@/lib/budget';
import { applyBudgetReference, canUndoBudgetReference, ELECTRICITY_BILLS, electricityReference, NATIONAL_BUDGET_REFERENCES, undoBudgetReference } from '@/lib/budget-references';
export function BudgetReferencePicker({line,retirement,onChange}:{line:BudgetLine;retirement:boolean;onChange:(line:BudgetLine)=>void}){
 const [selection,setSelection]=useState(''),[state,setState]=useState('');
 const reference=selection==='electricity'?electricityReference(state):NATIONAL_BUDGET_REFERENCES.find(r=>r.id===selection);
 return <details><summary>Use a Public Reference (Optional)</summary><p className="field-help">Choose a starting point only when it fits this row. These are historical public averages, not your spending history. Existing values change only when you apply a choice.</p><FormGrid as="div" className="budget-fields"><label className="budget-field"><span>Reference</span><select aria-label="Budget Reference" value={selection} onChange={e=>setSelection(e.target.value)}><option value="">Select Reference</option>{NATIONAL_BUDGET_REFERENCES.map(r=><option key={r.id} value={r.id}>{r.label} — U.S. 2024</option>)}<option value="electricity">Electricity — State 2024</option></select></label>{selection==='electricity'&&<label className="budget-field"><span>Reference State</span><select aria-label="Reference State" value={state} onChange={e=>setState(e.target.value)}><option value="">Select State</option>{Object.keys(ELECTRICITY_BILLS).sort().map(s=><option key={s}>{s}</option>)}</select></label>}</FormGrid>{reference&&<div className="budget-reference-card"><strong>{new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(reference.monthly)} / Month · {reference.geography}</strong><p className="field-help">{reference.population}. {reference.method}. Observation: {reference.period}; published {reference.published}; verified September 7, 2026. It is not inflation-adjusted to today and does not scale with family size.</p><a href={reference.source} target="_blank" rel="noreferrer">Official Source</a><Button variant="outline" onClick={()=>onChange(applyBudgetReference(line,reference,retirement?'retirement':'current'))}>Apply to {retirement?'Retirement':'Current'} Amount</Button></div>}{line.reference&&<p className="field-help">Source receipt: {line.reference.reference.label}, {line.reference.reference.geography}, {line.reference.reference.period}. {canUndoBudgetReference(line)?<Button variant="ghost" onClick={()=>onChange(undoBudgetReference(line))}>Undo Reference Amount</Button>:'Amount or frequency has been edited; Undo is unavailable to protect your change.'}</p>}</details>;
}
