"use client";
import { FormGrid, Stack } from '@/components/ui/planner-layout';
import { useMemo, useState } from 'react';
import { BookOpen, CalendarDays, Plus, Settings2, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Amount, FrequencySelect } from '@/components/budget-editor';
import { BUDGET_CATEGORIES, FREQUENCIES, retirementAmount, type BudgetLine } from '@/lib/budget';
import { matchingReference, suggestedBills } from '@/lib/budget-catalog';
import { applyBudgetReference, canUndoBudgetReference, undoBudgetReference } from '@/lib/budget-references';
import { budgetView, budgetViewMonth } from '@/lib/budget-view';
import type { PlannerData } from '@/lib/planner';
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
export function CompactBudgetEditor({plan,onChange,retirement=false}:{plan:PlannerData;onChange:(p:PlannerData)=>void;retirement?:boolean}) {
  const budget=plan.budget;
  const [selected,setSelected]=useState('');
  const [dialog,setDialog]=useState<{line:BudgetLine;mode:'timing'|'settings'|'reference'}|null>(null);
  const month=selected||budgetViewMonth(plan,retirement);
  const view=useMemo(()=>budgetView(plan,month),[plan,month]);
  const suggestions=suggestedBills(budget.lines,retirement);
  const groups=[...new Set([...BUDGET_CATEGORIES,...budget.lines.map(l=>l.category)])];
  const patchBudget=(patch:Partial<PlannerData['budget']>)=>onChange({...plan,budget:{...budget,...patch}});
  const update=(line:BudgetLine,patch:Partial<BudgetLine>)=>{
    const next={...line,...patch};
    patchBudget({reviewed:false,lines:budget.lines.some(l=>l.id===line.id)?budget.lines.map(l=>l.id===line.id?next:l):[...budget.lines,next]});
    if(dialog?.line.id===line.id)setDialog({...dialog,line:next});
  };
  const active=dialog?(budget.lines.find(l=>l.id===dialog.line.id)??dialog.line):null;
  const reference=active?matchingReference(active,plan.household.state):null;
  return <Stack as="div" className="budget-flow compact-budget">
    <div className="section-heading"><h1>{retirement?'Retirement Budget':'Current Budget'}</h1><p>{retirement?'Keep what fits. Change only what retirement changes.':'Expand a category and enter your bills. Income and linked costs are already connected.'}</p></div>
    <div className="budget-toolbar"><label className="budget-field"><span>Budget Month</span><Input aria-label="Budget Month" type="month" min={`${budget.timeline?.startYear??new Date().getFullYear()}-01`} value={month} onChange={e=>{if(/^\d{4}-(0[1-9]|1[0-2])$/.test(e.target.value)&&e.target.value>=`${budget.timeline?.startYear??new Date().getFullYear()}-01`)setSelected(e.target.value);}}/></label><p className="field-help">Planned cash for this month, including scheduled bills and inflation. Bill inputs use opening-year dollars.</p></div>
    <div className="budget-metrics"><div><span>Income</span><strong>{money(view.totalIncome)}</strong></div><div><span>Spending</span><strong>{money(view.totalSpending)}</strong></div><div><span>{view.margin<0?'Funding Needed':'After Planned Savings'}</span><strong>{money(Math.abs(view.margin))}</strong></div></div>
    {view.issues.map(issue=><p role="status" className="notice" key={issue}>{issue}</p>)}
    {view.calendar.missingAmounts>0&&<p role="status">{view.calendar.missingAmounts} entered items still need an amount. Unused suggestions are not counted.</p>}
    <section className="compact-section"><h2>Income</h2>{view.income.length?view.income.map((r,i)=><div className="compact-linked" key={`${r.id}-${i}`}><span>{r.name}<small>{r.source}</small></span><strong>{r.amount===null?'Withholding Needed':money(r.amount)}</strong></div>):<p className="field-help">Add pay in Household and benefits in Pensions & Social Security.</p>}<p className="field-help">Net deposits after entered withholding. Portfolio funding and year-end tax settlement appear in Plan Summary.</p></section>
    <section className="compact-section"><h2>Spending</h2><div className="compact-column-labels"><span>Category / Bill</span><span>Per Payment</span><span>Tools</span></div>
      {groups.map(group=>{
        const saved=budget.lines.filter(l=>l.category===group),shown=[...saved,...suggestions.filter(l=>l.category===group)];
        return <details className="compact-category" key={group}><summary><span>{group}<small>{saved.length?`${saved.length} entered`:'Add your bills'}</small></span><strong>{money(saved.reduce((n,l)=>n+(view.calendar.lines.find(r=>r.id===l.id)?.amount??0)*view.inflation,0))}</strong></summary>
          {shown.map(l=>{const value=retirement?retirementAmount(l):l.retirement.rule==='retirementOnly'?null:l.amount,ref=matchingReference(l,plan.household.state);
            return <div className="compact-bill" key={l.id} data-bill={l.id}>
              <div className="compact-name"><Input aria-label={`Bill Name — ${l.id}`} value={l.name} onChange={e=>update(l,{name:e.target.value})}/><small>{FREQUENCIES[l.frequency].label}{retirement?` · ${l.retirement.rule==='continue'?'Linked':l.retirement.rule==='stop'?'Stops':l.retirement.rule==='percent'?'Percentage Change':'Retirement Amount'}`:''}</small></div>
              <div className="input-affix compact-amount"><span>$</span><Input aria-label={`${retirement?'Retirement':'Current'} Amount — ${l.id}`} type="number" min={0} step="any" value={value??''} onFocus={e=>e.currentTarget.select()} onChange={e=>{const amount=e.target.value===''?null:e.target.valueAsNumber;update(l,retirement?{retirement:{...l.retirement,rule:l.retirement.rule==='retirementOnly'?'retirementOnly':'replace',amount}}:{amount});}}/></div>
              <div className="compact-tools"><Button variant="ghost" size="icon" aria-label={`Bill Timing — ${l.id}`} title="Bill Timing" onClick={()=>setDialog({line:l,mode:'timing'})}><CalendarDays/></Button><Button variant="ghost" size="icon" aria-label={`Bill Settings — ${l.id}`} title="Bill Settings" onClick={()=>setDialog({line:l,mode:'settings'})}><Settings2/></Button>{ref&&<Button variant="ghost" size="icon" aria-label={`Public Reference — ${l.id}`} title="Public Reference" onClick={()=>setDialog({line:l,mode:'reference'})}><BookOpen/></Button>}</div>
            </div>;
          })}
          <Button variant="ghost" onClick={()=>{const l:BudgetLine={id:crypto.randomUUID(),name:'New Bill',category:group,amount:null,frequency:'monthly',essential:false,owner:'household',nextDueDate:'',endDate:'',retirement:{rule:retirement?'retirementOnly':'continue',amount:null,reason:''}};update(l,{});setDialog({line:l,mode:'settings'});}}><Plus/>Add {group} Bill</Button>
        </details>;
      })}
      <details className="compact-category" open><summary><span>Linked Costs<small>Debts, housing, health and timed expenses</small></span><strong>{money(view.linked.reduce((n,r)=>n+(r.amount??0),0))}</strong></summary>{view.linked.map(r=><div className="compact-linked" key={r.id}><span>{r.name}<small>{r.source}</small></span><strong>{money(r.amount??0)}</strong></div>)}{!view.linked.length&&<p className="field-help">No linked payments in this month.</p>}<p className="field-help">Paid-off loans disappear here. Tax and insurance continue after mortgage payoff. Do not repeat these costs above.</p></details>
    </section>
    {!retirement&&<details className="compact-section"><summary>Savings Transfers · {money(view.savings)} / Month</summary><p className="field-help">Transfers from take-home pay, separate from payroll savings.</p>{(budget.savings??[]).map(s=><FormGrid as="div" className="budget-fields" key={s.id}><Input aria-label="Saving Description" value={s.name} onChange={e=>patchBudget({savings:budget.savings!.map(v=>v.id===s.id?{...v,name:e.target.value}:v)})}/><Amount label="Saving per Payment" value={s.amount} onChange={amount=>patchBudget({savings:budget.savings!.map(v=>v.id===s.id?{...v,amount}:v)})}/><FrequencySelect value={s.frequency} onChange={frequency=>patchBudget({savings:budget.savings!.map(v=>v.id===s.id?{...v,frequency}:v)})}/><select aria-label="Savings Account" value={s.accountId} onChange={e=>patchBudget({savings:budget.savings!.map(v=>v.id===s.id?{...v,accountId:e.target.value}:v)})}><option value="">Select Account</option>{plan.accounts.map(a=><option key={a.id} value={a.id}>{a.name||a.kind}</option>)}</select><Button variant="ghost" onClick={()=>patchBudget({savings:budget.savings!.filter(v=>v.id!==s.id)})}>Remove Saving</Button></FormGrid>)}<Button variant="outline" onClick={()=>patchBudget({savings:[...(budget.savings??[]),{id:crypto.randomUUID(),name:'',accountId:'',amount:null,frequency:'monthly',owner:'household'}]})}>Add Saving</Button></details>}
    {retirement&&<section className="compact-section"><h2>Use This Budget</h2>{budget.retirementSpendingSource==='legacy'&&plan.assumptions.annualSpending>0&&<p>Previously entered aggregate: {money(plan.assumptions.annualSpending)} / year. Allocate it to bills before selecting the worksheet; the two are never added together.</p>}<label className="budget-field"><span>Retirement Spending Source</span><select aria-label="Retirement Spending Source" value={budget.retirementSpendingSource} onChange={e=>patchBudget({retirementSpendingSource:e.target.value as 'legacy'|'worksheet',reviewed:false})}><option value="worksheet">Linked Budget Worksheet</option>{budget.retirementSpendingSource==='legacy'&&<option value="legacy">Previously Entered Aggregate</option>}</select></label><label className="budget-check"><input type="checkbox" checked={budget.reviewed} onChange={e=>patchBudget({reviewed:e.target.checked,retirementSpendingSource:e.target.checked?'worksheet':budget.retirementSpendingSource})}/>I have reviewed these bills and the linked costs.</label></section>}
    <Dialog open={!!dialog} onOpenChange={open=>{if(!open)setDialog(null);}}><DialogContent className="budget-row-dialog"><DialogHeader><DialogTitle>{active?.name||'Bill'} · {dialog?.mode==='timing'?'Bill Timing':dialog?.mode==='reference'?'Public Reference':'Bill Settings'}</DialogTitle><DialogDescription>Changes apply to this bill and its linked retirement rule.</DialogDescription></DialogHeader>
      {active&&dialog?.mode==='timing'&&<Stack as="div" className="budget-flow"><FrequencySelect value={active.frequency} onChange={frequency=>update(active,{frequency})}/><label className="budget-field">Next Due Date<Input aria-label="Next Due Date" type="date" value={active.nextDueDate} onChange={e=>update(active,{nextDueDate:e.target.value})}/></label><label className="budget-field">Final Due Date<Input aria-label="Final Due Date" type="date" value={active.endDate} onChange={e=>update(active,{endDate:e.target.value})}/></label><p className="field-help">Without dates, monthly averages are used. Twice monthly means the 15th and last day.</p>
        <details><summary>Dated Changes</summary>{(budget.overrides??[]).filter(o=>o.lineId===active.id).map(o=><FormGrid as="div" className="budget-fields" key={o.id}><label>From Month<Input aria-label="From Month" type="month" value={o.fromMonth} onChange={e=>patchBudget({reviewed:false,overrides:budget.overrides!.map(v=>v.id===o.id?{...v,fromMonth:e.target.value}:v)})}/></label><label>Through Month<Input aria-label="Through Month" type="month" value={o.throughMonth} onChange={e=>patchBudget({reviewed:false,overrides:budget.overrides!.map(v=>v.id===o.id?{...v,throughMonth:e.target.value}:v)})}/></label><Amount label="Dated Amount per Payment" value={o.amount} onChange={amount=>patchBudget({reviewed:false,overrides:budget.overrides!.map(v=>v.id===o.id?{...v,amount}:v)})}/><Button variant="ghost" onClick={()=>patchBudget({reviewed:false,overrides:budget.overrides!.filter(v=>v.id!==o.id)})}>Remove Dated Change</Button></FormGrid>)}<Button variant="outline" disabled={!budget.lines.some(l=>l.id===active.id)} onClick={()=>patchBudget({reviewed:false,overrides:[...(budget.overrides??[]),{id:crypto.randomUUID(),lineId:active.id,fromMonth:month,throughMonth:month,amount:active.amount}]})}>Add Dated Change</Button></details></Stack>}
      {active&&dialog?.mode==='settings'&&<Stack as="div" className="budget-flow"><label className="budget-field">Bill Name<Input aria-label="Bill Name" value={active.name} onChange={e=>update(active,{name:e.target.value})}/></label><label className="budget-field">Category<select aria-label="Category" value={active.category} onChange={e=>update(active,{category:e.target.value})}>{groups.map(c=><option key={c}>{c}</option>)}</select></label><label className="budget-check"><input type="checkbox" checked={active.essential} onChange={e=>update(active,{essential:e.target.checked})}/>Essential Cost</label><label className="budget-field">In Retirement<select aria-label="In Retirement" value={active.retirement.rule} onChange={e=>update(active,{retirement:{...active.retirement,rule:e.target.value as BudgetLine['retirement']['rule']}})}><option value="continue">Continue Current Amount</option><option value="stop">Stop</option><option value="replace">Replace Amount</option><option value="percent">Change by Percentage</option><option value="retirementOnly">New Retirement Cost</option></select></label>{['replace','percent','retirementOnly'].includes(active.retirement.rule)&&<Amount label={active.retirement.rule==='percent'?'Change by Percentage':'Retirement Amount'} percent={active.retirement.rule==='percent'} value={active.retirement.amount} onChange={amount=>update(active,{retirement:{...active.retirement,amount}})}/>}<label className="budget-field">Retirement Trigger<select aria-label="Retirement Trigger" value={active.owner} onChange={e=>update(active,{owner:e.target.value as BudgetLine['owner']})}><option value="household">Full Household Retirement</option><option value="you">Your Retirement</option>{plan.household.maritalStatus==='married'&&<option value="partner">Partner Retirement</option>}</select></label><label className="budget-field">Reason<Input value={active.retirement.reason} onChange={e=>update(active,{retirement:{...active.retirement,reason:e.target.value}})}/></label>{!!active.allocations?.length&&<p className="field-help">The imported breakdown is retained in your data. Only this bill total is counted.</p>}<Button variant="destructive" onClick={()=>{patchBudget({reviewed:false,lines:budget.lines.filter(l=>l.id!==active.id),overrides:budget.overrides?.filter(o=>o.lineId!==active.id)});setDialog(null);}}><Trash2/>Remove Bill</Button></Stack>}
      {active&&dialog?.mode==='reference'&&reference&&<Stack as="div" className="budget-flow"><strong>{money(reference.monthly)} / Month · {reference.geography} · {reference.period}</strong><p className="field-help">{reference.population}. Historical average, not a personalized target.</p><Button onClick={()=>update(active,applyBudgetReference(active,reference,retirement?'retirement':'current'))}>Apply Reference</Button>{canUndoBudgetReference(active)&&<Button variant="outline" onClick={()=>update(active,{...undoBudgetReference(active),reference:undefined})}>Undo Reference Amount</Button>}</Stack>}
    </DialogContent></Dialog>
  </Stack>;
}
