"use client";
import { FormGrid, PlannerCard } from '@/components/ui/planner-layout';
import { Plus, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Amount } from '@/components/budget-editor';
import { newEducationAccount, projectEducation, linkEducationBudget, type EducationAccount } from '@/lib/education';
import type { PlannerData } from '@/lib/planner';
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
export function EducationAccounts({plan,onChange}:{plan:PlannerData;onChange:(p:PlannerData)=>void}){
 const accounts=plan.education?.accounts??[],dependents=plan.household.dependents??[],set=(accounts:EducationAccount[])=>onChange({...plan,education:{accounts}});
 return <PlannerCard as="section" stack className="panel budget-flow"><div className="budget-toolbar"><div><h2>College / 529 Accounts</h2><p className="field-help">Education assets are tracked separately from retirement withdrawal funds.</p></div><Button variant="outline" disabled={accounts.length>=24} onClick={()=>set([...accounts,newEducationAccount(crypto.randomUUID())])}><Plus size={16}/>Add 529 Account</Button></div>{accounts.map((a,i)=>{const change=(patch:Partial<EducationAccount>)=>set(accounts.map(x=>x.id===a.id?{...x,...patch}:x)),d=dependents.find(d=>d.id===a.beneficiaryId),linked=plan.budget.lines.find(l=>l.id===`education-saving:${a.id}`),valid=!!plan.budget.timeline?.startYear&&!!d?.collegeStartYear&&d.collegeStartYear>plan.budget.timeline.startYear&&a.monthlyContribution!==null;
 return <details className="oe-person @container" key={a.id}><summary><strong>529 Account {i+1}</strong><span>{d?`Dependent ${dependents.indexOf(d)+1}`:'Assign Beneficiary'} · {a.balance===null?'Balance Needed':money(a.balance)}</span></summary><div className="oe-detail"><FormGrid as="div" className="oe-fields"><label className="budget-field">Beneficiary<select aria-label="529 Beneficiary" value={a.beneficiaryId} onChange={v=>change({beneficiaryId:v.target.value})}><option value="">Choose Household Dependent</option>{dependents.map((d,i)=><option key={d.id} value={d.id}>Dependent {i+1}</option>)}</select></label><Amount label="529 Opening Balance" value={a.balance} onChange={balance=>change({balance})}/><Amount label="529 Monthly Contribution" value={a.monthlyContribution} onChange={monthlyContribution=>change({monthlyContribution})}/><Amount label="529 Annual Return Assumption" percent value={a.returnRate} onChange={returnRate=>change({returnRate})}/></FormGrid><div className="oe-inline"><Button variant="outline" disabled={!valid} onClick={()=>onChange(linkEducationBudget(plan,a.id))}>{linked?'Update':'Add'} Budget Provision</Button><Button variant="ghost" onClick={()=>set(accounts.filter(x=>x.id!==a.id))}><Trash2 size={16}/>Remove 529 Account {i+1}</Button></div><p className="field-help">{linked?`Existing budget provision: ${money(linked.amount??0)} / month through ${linked.endDate}. Update it after editing this account or its goal.`:'Add a provision to include these deposits in current and retirement cash needs until college starts. Existing manually entered college saving is not removed; reconcile duplicates.'} The education projection assumes deposits are funded. Budget provisions remain if an account is removed, so review them explicitly.</p></div></details>;})}<p className="field-help">Set college timing and one cost goal per dependent in Household. Contributions stop before college; qualified expenses are drawn at the start of each college year. No federal contribution deduction, state incentive or nonqualified distribution tax is assumed.</p></PlannerCard>;
}
export function EducationSummary({plan}:{plan:PlannerData}){
 if(!plan.education?.accounts.length)return null;const result=projectEducation(plan);
 return <PlannerCard as="section" stack className="panel budget-flow education-summary"><h2>College / 529 Outlook</h2><p className="field-help">A separate education funding illustration. These balances are not available to retirement withdrawals or included in retirement net worth. Projected deposits assume funding; the household budget checks linked provisions separately.</p>{result.issues.map(s=><p key={s}>{s}</p>)}{result.goals.map(g=><div className="budget-card @container" key={g.id}><h3>{g.label}</h3>{g.issues.length?<ul>{g.issues.map(s=><li key={s}>{s}</li>)}</ul>:g.rows.length>0&&<><div className="oe-result-grid"><div><small>At College Start</small><strong>{money(g.collegeOpening)}</strong></div><div><small>College Cost Goal</small><strong>{money(g.totalCost)}</strong></div><div><small>Additional Funding Needed</small><strong>{money(g.totalGap)}</strong></div></div><EducationChart rows={g.rows}/><details><summary>Annual Education Ledger</summary><div className="oe-ledger">{g.rows.map(r=><div key={r.year}><strong>{r.year}</strong><span>Opening {money(r.opening)}<br/>Deposits {money(r.contributions)}<br/>Growth {money(r.growth)}</span><span>Cost {money(r.cost)}<br/>529 Paid {money(r.withdrawal)}<br/>Gap {money(r.gap)}</span><span>Ending {money(r.ending)}</span></div>)}</div></details></>}</div>)}<p className="field-help">Constant assumed returns and costs are not guarantees. College costs are entered in opening-year dollars and inflated once. Multiple accounts for one beneficiary fund one goal. Federal tax-free withdrawals assume qualified expenses and no double use for education credits; scholarships, state tax and nonqualified withdrawals need separate review.</p></PlannerCard>;
}
function EducationChart({rows}:{rows:ReturnType<typeof projectEducation>['goals'][number]['rows']}){const max=Math.max(1,...rows.map(r=>Math.max(r.ending,r.cost))),w=500/rows.length;return <svg className="education-chart" viewBox="0 0 600 200" role="img" aria-label="529 ending balance and college cost by year"><title>Teal: Ending 529 Balance. Amber: Annual College Cost.</title>{rows.map((r,i)=><g key={r.year}><rect x={60+i*w} y={160-r.ending/max*135} width={w*.4} height={r.ending/max*135} fill="#167a70"><title>{r.year} balance: {money(r.ending)}</title></rect><rect x={60+i*w+w*.4} y={160-r.cost/max*135} width={w*.4} height={r.cost/max*135} fill="#b47819"><title>{r.year} cost: {money(r.cost)}</title></rect>{(i===0||i===rows.length-1||rows.length<=6)&&<text x={60+i*w} y="183" fontSize="12">{r.year}</text>}</g>)}<text x="60" y="14" fontSize="12">Teal: Ending Balance · Amber: College Cost</text></svg>;}
