"use client";
import { useRef, useState } from 'react';
import { Download, Upload } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { exportEmployerOptions, parseEmployerOptions, replaceEmployerOptions } from '@/lib/enrollment-sharing';
import type { Enrollment, HealthOption } from '@/lib/enrollment';
export function EnrollmentSharing({enrollment:e,onChange}:{enrollment:Enrollment;onChange:(e:Enrollment)=>void}){
  const file=useRef<HTMLInputElement>(null),[pending,setPending]=useState<HealthOption[]|null>(null),[error,setError]=useState(''),[review,setReview]=useState(false);
  const download=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(exportEmployerOptions(e.options),null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='employer-health-options.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setReview(false);};
  return <div className="oe-sharing"><div className="oe-inline"><Button variant="outline" disabled={!e.options.length} onClick={()=>setReview(!review)}><Download size={16}/>Share Employer Options</Button><Button variant="outline" onClick={()=>file.current?.click()}><Upload size={16}/>Import Employer Options</Button></div><input ref={file} type="file" accept=".json,application/json" hidden aria-label="Employer Options File" onChange={async ev=>{const f=ev.target.files?.[0];ev.target.value='';if(!f)return;setError('');setPending(null);try{if(f.size>100000)throw Error('Options file must be under 100 KB.');setPending(parseEmployerOptions(JSON.parse(await f.text())));}catch(err){setError(err instanceof Error?err.message:'Unable to read options file.');}}}/>{error&&<p role="alert">{error}</p>}
    {review&&<div className="oe-detail" role="region" aria-label="Employer Export Review"><strong>{e.options.length} Options · Plan Terms Only</strong><p>Includes premiums, pay frequency, deductible/OOP rules, coinsurance, network and employer HSA funding. Labels are replaced with numbered options. No people, care items, prescriptions, personal HSA balances, contributions, tax rates or other plan sections are included.</p><p className="field-help">Verify these are standard employer terms for the coverage tier you intend to share, not personalized quotes. Share the relevant tier and benefits documents separately; recipients must confirm their own care coverage and eligibility.</p><ol>{e.options.map((_,i)=><li key={i}>Employer Option {i+1}</li>)}</ol><div className="oe-inline"><Button onClick={download}>Download Terms Only</Button><Button variant="ghost" onClick={()=>setReview(false)}>Cancel Export</Button></div></div>}
    {pending&&<div className="oe-detail" role="region" aria-label="Employer Import Review"><strong>Replace Health Options with {pending.length} Employer Options?</strong><p>Your household, care entries and other plan sections stay intact. Current option-specific rules and HSA assumptions will be replaced. Confirm premiums for your tier, prescription coverage and personal HSA settings after import.</p><div className="oe-inline"><Button onClick={()=>{onChange(replaceEmployerOptions(e,pending));setPending(null);}}>Replace Health Options</Button><Button variant="ghost" onClick={()=>setPending(null)}>Cancel Import</Button></div></div>}
  </div>;
}
