import { ActionRow, FormGrid } from '@/components/ui/planner-layout';
import { applyPublishedBenefits, publishedBenefits, FEHB_BENEFITS } from '@/lib/federal-benefits';
import { useState, type ReactNode } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { FEHB, blankFederal, federalCandidates, federalDraft, federalLocation, federalReviewIssues, type FederalPlan } from '@/lib/federal-health';
import { compareHealth, type Enrollment, type HealthOption } from '@/lib/enrollment';
const money=(n:number|null)=>n===null?'Needs Review':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n);
export function FederalHealth({enrollment:e,onChange,renderOption,householdZip}:{enrollment:Enrollment;onChange:(e:Enrollment)=>void;renderOption:(p:HealthOption,i:number,people:Enrollment['people'])=>ReactNode;householdZip?:string}) {
  const f=e.federal??blankFederal(),[query,setQuery]=useState(''),[showUnknown,setShowUnknown]=useState(false),[limit,setLimit]=useState(8);
  const set=(patch:Partial<typeof f>)=>onChange({...e,federal:{...f,...patch}});
  const matching=FEHB.plans.filter(p=>federalLocation(p,f)==='match'),unknown=FEHB.plans.filter(p=>federalLocation(p,f)==='unknown');
  const visible=(showUnknown?[...matching,...unknown]:matching).filter(p=>(p.name+' '+p.option+' '+p.planCode).toLowerCase().includes(query.toLowerCase()));
  const reviews=federalCandidates(e),complete=reviews.filter(c=>!c.result.issues.length).length;
  const states=[...new Set(FEHB.plans.flatMap(p=>p.regions.map(r=>r[0])))].filter(Boolean).sort();
  const counties=[...new Map(FEHB.plans.flatMap(p=>p.regions.filter(r=>r[0]===f.state&&r[2]).map(r=>[r[2],r[3]] as [string,string]))).entries()].sort((a,b)=>a[1].localeCompare(b[1]));
  const add=(p:FederalPlan,tier:string)=>{const t=p.tiers.find(t=>t.tier===tier);if(!t)return;const option=federalDraft(p,t,f.employee);if(f.options.some(o=>o.id===option.id))return;onChange({...e,startMonth:e.startMonth||`${FEHB.year}-01`,federal:{...f,options:[...f.options,option]}});};
  return <div className="fehb-panel"><div className="oe-inline"><h3>Federal Employee Options · {FEHB.year}</h3><span className="field-help">{FEHB.counts.planNames} Plan Names · {FEHB.counts.options} Options</span></div><FormGrid as="div" className="oe-fields">
    <label className="budget-field"><span>Federal Employee</span><select aria-label="Federal Employee" value={f.employee} onChange={ev=>set({employee:ev.target.value as typeof f.employee,eligible:false})}><option value="">Choose Employee</option><option value="you">You</option><option value="partner">Partner</option></select></label>
    <label className="budget-field"><span>Home or Work ZIP</span><Input aria-label="Federal Home or Work ZIP" inputMode="numeric" maxLength={5} value={f.zip} onChange={ev=>set({zip:ev.target.value,county:''})}/></label>
    <label className="budget-field"><span>State / Territory</span><select aria-label="Federal Service State" value={f.state} onChange={ev=>set({state:ev.target.value,county:''})}><option value="">Choose Location</option>{states.map(s=><option key={s}>{s}</option>)}</select></label>
    <label className="budget-field"><span>County (If Needed)</span><select aria-label="Federal Service County" value={f.county} onChange={ev=>set({county:ev.target.value})}><option value="">Choose County</option>{counties.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>
  </FormGrid>{householdZip&&<Button variant="ghost" onClick={()=>set({zip:householdZip,county:''})}>Use Household ZIP</Button>}
  <label className="budget-field"><span>Employee Rate Category</span><select aria-label="Employee Rate Category" value={f.eligible?'active':''} onChange={ev=>set({eligible:ev.target.value==='active'})}><option value="">Choose Category</option><option value="active">Active Federal Employee (Non-Postal)</option><option value="other">Postal, Retired, or Other — Use Your Own Rates</option></select></label>
  <p className="field-help">County helps resolve plans whose service areas are not defined by ZIP. Location stays in this browser. PSHB, annuitant and other special rate categories need their own rates and are not ranked here. Confirm carrier membership requirements and provider participation for each option.</p>
  <p role="status"><strong>{complete} Completed Federal Comparisons</strong> · Up to three lowest modeled costs appear alongside private options below. {matching.length} options match the location; {unknown.length} need location review. Options with missing inputs are not ranked.</p><label className="budget-check"><input type="checkbox" checked={f.showAll??false} onChange={ev=>set({showAll:ev.target.checked})}/>Show all completed federal comparisons</label>
  <details><summary>Browse Federal Options and Published Benefits</summary><div className="oe-detail"><Input aria-label="Search Federal Options" placeholder="Filter plan name or code" value={query} onChange={ev=>{setQuery(ev.target.value);setLimit(8);}}/><label className="budget-check"><input type="checkbox" checked={showUnknown} onChange={ev=>setShowUnknown(ev.target.checked)}/>Include options needing location review</label><p className="field-help">Alphabetical directory, not a cost ranking. Review the enrollment tier matching the people you intend to cover. For two people, compare both Self Plus One and Family.</p>
  {visible.slice(0,limit).map(p=><details className="fehb-candidate" key={p.id}><summary><strong>{p.name} · {p.option}</strong><span>{federalLocation(p,f)==='match'?'Location Match':'Location Needs Review'} · {p.kind}</span></summary><div className="oe-detail"><p>{p.account} · {p.network} · Brochure {p.brochure}</p>{p.tiers.map(t=><div className="fehb-tier" key={t.code}><span><strong>{t.tier==='self'?'Self':t.tier==='plusOne'?'Self Plus One':'Self & Family'} · {t.code}</strong><br/>{money(t.biweekly)} / biweekly · {money(t.biweekly*26)} / year<br/>Published tier deductible {money(t.deductible)} · OOP max {money(t.maximum)}</span><Button variant="outline" disabled={!f.employee||!f.eligible||f.options.length>=12||f.options.some(o=>o.id===`fehb-${t.code}`)} onClick={()=>add(p,t.tier)}>Add {t.code}</Button></div>)}<SourceTerms plan={p}/></div></details>)}{!visible.length&&<p>No matching entries. Check the location or show options needing review.</p>}{visible.length>limit&&<Button variant="outline" onClick={()=>setLimit(limit+12)}>Show More ({visible.length-limit} Remaining)</Button>}</div></details>
  {f.options.map((o,i)=>{const covered=o.coveredPersonIds?e.people.filter(p=>o.coveredPersonIds!.includes(p.id)):e.people;const p=FEHB.plans.find(p=>p.id===o.federalReference?.id),groupResult=compareHealth({...e,people:covered,...(covered.length!==e.people.length?{waivers:[]}: {})},o),review={result:{...groupResult,issues:[...groupResult.issues,...federalReviewIssues(e,o,covered)]}};return <details className="fehb-review" key={o.id}><summary><strong>{o.label}</strong><span>{review?.result.issues.length?`${review.result.issues.length} Missing Inputs`:money(review?.result.netCost??0)+' / Year'}</span></summary><div className="oe-detail">{p&&<><SourceTerms plan={p}/><p className="field-help">Published deductibles, individual/family limits and mapped service prices fill automatically. Enter expected care once above, then choose each prescription’s formulary tier below. Association dues, provider participation and special coverage remain plan-specific.</p>{o.federalReference?.version===FEHB.version&&o.federalReference?.benefitVersion!==FEHB_BENEFITS.version&&<Button variant="outline" onClick={()=>set({options:f.options.map(x=>x.id===o.id?applyPublishedBenefits(x):x)})}>Apply Current Published Benefits</Button>}{o.federalReference?.version!==FEHB.version&&<p className="field-help">This option uses an older premium/catalog edition. Add its current enrollment code from the directory to compare current rates; the saved values are retained here.</p>}<p className="field-help">{Object.keys(publishedBenefits(o)?.services??{}).length} published service rules available. {publishedBenefits(o)?.scope??'Uses exact published in-network prices. Highlighted fields need information that could not be mapped reliably.'}</p></>}<fieldset className="fehb-group @container"><legend>People Covered by This Federal Tier</legend><ActionRow as="div" className="oe-actions">{e.people.map((person,pi)=><label className="budget-check" key={person.id}><input type="checkbox" checked={covered.some(p=>p.id===person.id)} onChange={ev=>set({options:f.options.map(x=>x.id===o.id?{...x,coveredPersonIds:ev.target.checked?[...covered.map(p=>p.id),person.id]:covered.filter(p=>p.id!==person.id).map(p=>p.id),federalReference:{...x.federalReference!,reviewed:false}}:x)})}/>Person {pi+1}</label>)}</ActionRow></fieldset>{renderOption(o,i,covered)}<label className="budget-check"><input type="checkbox" checked={o.federalReference?.pinned??false} onChange={ev=>set({options:f.options.map(x=>x.id===o.id?{...x,federalReference:{...x.federalReference!,pinned:ev.target.checked}}:x)})}/>Keep this option visible when complete, even outside the top three</label>{covered.length!==e.people.length&&<p className="field-help">This is a partial household group. Compare it through Household Coverage Arrangements; waiver income is applied there after both groups are selected.</p>}{federalReviewIssues(e,o,covered).length>0&&<p className="field-help">{federalReviewIssues(e,o,covered).join(' ')}</p>}</div></details>;})}
  <p className="field-help">Leaving FEHB may affect retirement continuation: review the enrollment and five-year coverage requirements before switching. A lower annual cost is not an enrollment recommendation. <a href="https://www.opm.gov/support/retirement/faq/health-care-coverage/" target="_blank" rel="noreferrer">OPM retirement guidance</a>.</p><p className="field-help">OPM {FEHB.year} workbooks and brochures, benefit mapping reviewed {FEHB_BENEFITS.reviewedAt}. Saved plan editions are preserved; published updates require an explicit action. <a href="https://www.opm.gov/healthcare-insurance/healthcare/transparency-in-healthcare/public-use-files/" target="_blank" rel="noreferrer">Official source files</a>.</p>
  </div>;
}
function SourceTerms({plan:p}:{plan:FederalPlan}){const [filter,setFilter]=useState('');return <details><summary>Source Benefits & Provider / Formulary Links</summary><div className="oe-detail"><ActionRow as="div" className="oe-actions"><a href={FEHB_BENEFITS.sources[FEHB_BENEFITS.plans[p.id]?.brochure??'']?.url} target="_blank" rel="noreferrer">OPM Plan-Year Brochure</a>{Object.entries(p.links).map(([label,url])=><a key={label} href={url} target="_blank" rel="noreferrer">{label==='benefits'?'Benefit Documents':label==='providers'?'Provider Directory':'Formulary'}</a>)}</ActionRow><Input aria-label={`Filter Source Benefits ${p.id}`} placeholder="Find a benefit, e.g. prescription or specialist" value={filter} onChange={e=>setFilter(e.target.value)}/><dl className="fehb-terms">{Object.entries(p.terms).filter(([key])=>!filter||key.toLowerCase().includes(filter.toLowerCase())).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl></div></details>;}
