"use client";
import { FormGrid, PlannerCard } from '@/components/ui/planner-layout';
import { Plus, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Amount } from '@/components/budget-editor';
import { newDependent, type Dependent } from '@/lib/education';
import type { PlannerData } from '@/lib/planner';
export function HouseholdMembers({plan,onChange}:{plan:PlannerData;onChange:(p:PlannerData)=>void}){
 const people=plan.household.dependents??[],set=(dependents:Dependent[])=>onChange({...plan,household:{...plan.household,dependents}});
 return <PlannerCard as="section" stack className="panel budget-flow"><div className="budget-toolbar"><div><h2>Household Members</h2><p className="field-help">You{plan.household.maritalStatus==='married'?' + Partner':''} · {people.length} Dependents. Adult ages and retirement dates are above. No names or exact birth dates are needed.</p></div><Button variant="outline" disabled={people.length>=12} onClick={()=>set([...people,newDependent(crypto.randomUUID())])}><Plus size={16}/>Add Dependent</Button></div>{people.map((d,i)=>{const change=(patch:Partial<Dependent>)=>set(people.map(x=>x.id===d.id?{...x,...patch}:x));return <details className="oe-person @container" key={d.id}><summary><strong>Dependent {i+1}</strong><span>{d.birthYear?`Born ${d.birthYear}`:'Add Details'} · {(plan.education?.accounts??[]).filter(a=>a.beneficiaryId===d.id).length} Linked 529 Accounts</span></summary><div className="oe-detail"><Amount label="Dependent Birth Year" value={d.birthYear} unit="YYYY" onChange={birthYear=>change({birthYear})}/><details><summary>College Goal</summary>{d.birthYear!==null&&Number.isInteger(d.birthYear)&&d.birthYear+18>=2026&&d.birthYear+18<=2100&&<Button variant="ghost" onClick={()=>change({collegeStartYear:d.birthYear!+18})}>Use Age 18 Start ({d.birthYear+18})</Button>}<FormGrid as="div" className="oe-detail oe-fields"><Amount label="College Start Year" unit="YYYY" value={d.collegeStartYear} onChange={collegeStartYear=>change({collegeStartYear})}/><Amount label="College Years" unit="years" value={d.collegeYears} onChange={collegeYears=>change({collegeYears})}/><Amount label="Annual Qualified College Cost in Opening-Year Dollars" value={d.annualCost} onChange={annualCost=>change({annualCost})}/><Amount label="Annual College Cost Growth" percent value={d.costGrowth} onChange={costGrowth=>change({costGrowth})}/></FormGrid><p className="field-help">Use remaining qualified expenses after scholarships and costs assigned to tax credits. Enter balances and savings under Cash & Investments. A goal does not establish tax-dependent or HSA eligibility.</p></details><Button variant="ghost" onClick={()=>set(people.filter(x=>x.id!==d.id))}><Trash2 size={16}/>Remove Dependent {i+1}</Button><p className="field-help">Removing a dependent leaves their 529 records unassigned for review; it never deletes account balances or existing budget provisions.</p></div></details>;})}</PlannerCard>;
}
