"use client";
import { FormGrid, PlannerCard } from '@/components/ui/planner-layout';
import { ContributionEditor } from '@/components/contribution-editor';
import { Plus, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Amount, FrequencySelect } from '@/components/budget-editor';
import { payrollReconciliation } from '@/lib/budget-calendar';
import type { BudgetData } from '@/lib/budget';
import type { Account } from '@/lib/planner';
export function PayrollEditor({budget,onChange,accounts,married,birthYear,partnerBirthYear}:{budget:BudgetData;onChange:(b:BudgetData)=>void;accounts:Account[];married:boolean;birthYear:number;partnerBirthYear:number}){return (<PlannerCard as="section" stack className="panel budget-flow"><h2>Take-Home Pay</h2><p>Start with the amount deposited after deductions. Pension and Social Security remain in Benefits. Add the optional payroll breakdown when you are ready to use the monthly tax projection.</p>
      {budget.pay.map(p => <div className="budget-card @container" key={p.id}><FormGrid as="div" className="budget-fields">
        <label className="budget-field"><span>Pay Description</span><Input value={p.name} onChange={e => onChange({ ...budget, pay: budget.pay.map(q => q.id === p.id ? { ...q, name: e.target.value } : q) })} /></label>
        <Amount label="Take-Home per Payment" value={p.amount} onChange={amount => onChange({ ...budget, pay: budget.pay.map(q => q.id === p.id ? { ...q, amount } : q) })} />
        <FrequencySelect value={p.frequency} onChange={frequency => onChange({ ...budget, pay: budget.pay.map(q => q.id === p.id ? { ...q, frequency } : q) })} />
        <label className="budget-field"><span>Whose Pay?</span><select aria-label="Whose Pay?" value={p.owner} onChange={e => onChange({ ...budget, pay: budget.pay.map(q => q.id === p.id ? { ...q, owner: e.target.value as 'you' | 'partner' } : q) })}><option value="you">You</option>{married && <option value="partner">Partner</option>}</select></label>
        <label className="budget-field"><span>Next Pay Date (Optional)</span><Input type="date" value={p.nextPayDate} onChange={e => onChange({ ...budget, pay: budget.pay.map(q => q.id === p.id ? { ...q, nextPayDate: e.target.value } : q) })} /></label>
      </FormGrid><details><summary>Payroll Breakdown & Savings</summary><p>All amounts are per paycheck. Income-tax withholding excludes Social Security/Medicare payroll taxes; put those and insurance in Other Deductions. Taxable wages are the income-tax wage amount after eligible pretax deductions. Enter zero explicitly where appropriate.</p><FormGrid as="div" className="budget-fields">{(['gross','taxableWages','incomeTaxWithheld','otherDeductions','employeeSavings','employerSavings'] as const).map(key=><Amount key={key} label={{gross:'Gross Pay',taxableWages:'Taxable Wages',incomeTaxWithheld:'Income-Tax Withheld',otherDeductions:'Other Payroll Deductions',employeeSavings:'Employee Payroll Savings',employerSavings:'Employer Contributions'}[key]} value={p.payroll?.[key]??null} onChange={value=>onChange({...budget,pay:budget.pay.map(q=>q.id===p.id?{...q,payroll:{gross:null,taxableWages:null,incomeTaxWithheld:null,otherDeductions:null,employeeSavings:null,employerSavings:null,accountId:'',...q.payroll,[key]:value}}:q)})} />)}{!p.payroll?.allocations&&<label className="budget-field"><span>Payroll Savings Account</span><select aria-label="Payroll Savings Account" value={p.payroll?.accountId??''} onChange={e=>onChange({...budget,pay:budget.pay.map(q=>q.id===p.id?{...q,payroll:{gross:null,taxableWages:null,incomeTaxWithheld:null,otherDeductions:null,employeeSavings:null,employerSavings:null,...q.payroll,accountId:e.target.value}}:q)})}><option value="">Select Account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name||a.kind}</option>)}</select></label>}</FormGrid><ContributionEditor pay={p} birthYear={p.owner==='you'?birthYear:partnerBirthYear} accounts={accounts} onChange={pay=>onChange({...budget,pay:budget.pay.map(q=>q.id===p.id?pay:q)})}/><p className="field-help">{payrollReconciliation(p,accounts.map(a=>a.id)).reason} The contribution builder can split employee and employer funding between traditional and Roth accounts. Reapply after changing amounts; stale allocations block the tax projection.</p></details><Button variant="ghost" aria-label="Remove Pay Entry" onClick={() => onChange({ ...budget, pay: budget.pay.filter(q => q.id !== p.id) })}><Trash2 /> Remove</Button></div>)}
      <Button variant="outline" onClick={() => onChange({ ...budget, pay: [...budget.pay, { id: crypto.randomUUID(), name: '', owner: 'you', amount: null, frequency: 'monthly', nextPayDate: '' }] })}><Plus /> Add Take-Home Pay</Button>
    </PlannerCard>);}

