"use client";
import { useMemo, useState } from 'react';
import { Area, AreaChart, Bar, CartesianGrid, ComposedChart, Legend, Line, XAxis, YAxis } from 'recharts';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { ChartContainer, ChartTooltip, ChartTooltipContent } from '@/components/ui/chart';
import { Amount } from '@/components/budget-editor';
import { EMPTY_LAB, type Laboratory, type MonthlySettings, type PlanEvent, type SavedScenario } from '@/lib/monthly-model';
import { baselineSnapshot, comparison, scenarioChanges, scenarioIsStale } from '@/lib/scenarios';
import { projectMonthly, type MonthlyResult } from '@/lib/monthly-projection';
import type { PlannerData } from '@/lib/planner';

const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const compact=(n:number)=>new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:1}).format(n);
const config={portfolio:{label:'Investable Portfolio',color:'#2f7df4'},cash:{label:'Cash Reserves',color:'#11a68a'},income:{label:'Cash Income',color:'#11a68a'},outflow:{label:'Funded Spending & Settlement',color:'#d66b36'},net:{label:'Income Less Outflows',color:'#8567e8'}};

export function ScenarioComparison({plan}:{plan:PlannerData}) {
  const compared=useMemo(()=>comparison(plan,(plan.laboratory?.scenarios??[]).slice(0,3)),[plan]);
  if(!compared.scenarios.length)return null;
  const keys=[...new Set([...compared.baseline.years.map(y=>y.year),...compared.scenarios.flatMap(s=>s.result.years.map(y=>y.year))])].sort();
  const chart=keys.map(year=>({year,baseline:compared.baseline.years.find(y=>y.year===year)?.portfolio,...Object.fromEntries(compared.scenarios.map((s,i)=>[`scenario${i}`,s.comparable&&!s.stale?s.result.years.find(y=>y.year===year)?.portfolio:undefined]))}));
  return <section className="panel budget-flow"><h2>Compare Scenarios</h2><p>First three saved scenarios, on a shared time and dollar scale. Stale or unsupported scenarios retain their details but are excluded from this current-baseline chart. Outcomes are conditional estimates, not ranked recommendations.</p><ChartContainer config={config} className="h-[280px] w-full"><ComposedChart data={chart}><CartesianGrid vertical={false}/><XAxis dataKey="year"/><YAxis tickFormatter={compact}/><ChartTooltip content={<ChartTooltipContent/>}/><Legend/><Line dataKey="baseline" name="Current Baseline" stroke="#64748b" dot={false}/>{compared.scenarios.map((s,i)=><Line key={s.scenario.id} dataKey={`scenario${i}`} name={s.scenario.name||`Scenario ${i+1}`} stroke={['#2f7df4','#11a68a','#8567e8'][i]} dot={false}/>)}</ComposedChart></ChartContainer>{compared.scenarios.map((s,i)=><div className="budget-calendar-row" key={s.scenario.id}><strong>{s.scenario.name||`Scenario ${i+1}`}</strong><span>{s.stale?'Saved Baseline Changed':s.comparable?`Portfolio Δ ${money(s.deltaPortfolio)} · Tax Δ ${money(s.deltaTax)}`:'Needs Rule / Input Review'}</span></div>)}</section>;
}

export function MonthlyResults({ result, title='Monthly Planning Summary' }: {result:MonthlyResult;title?:string}) {
  const [selectedYear,setSelectedYear]=useState('');
  const [split,setSplit]=useState(false);
  const year=selectedYear||String(result.years[0]?.year??'');
  const rows=result.months.filter(r=>r.month.startsWith(year));
  const series=rows.map(r=>({...r,income:r.pay+r.pension+r.socialSecurity+r.cashInterest+r.eventIncome,outflow:r.spendingPaid+r.taxSettlement,net:r.pay+r.pension+r.socialSecurity+r.cashInterest+r.eventIncome-r.spendingPaid-r.taxSettlement+r.taxRefund}));
  const last=result.months.at(-1);
  return <section className="budget-flow monthly-results"><h2>{title}</h2>{result.issues.length>0&&<div className="panel budget-flow"><strong>{result.months.length?'Calculation Notes':'Inputs Needed'}</strong><ul>{result.issues.map(i=><li key={i}>{i}</li>)}</ul></div>}
    {last&&<><div className="budget-metrics"><div><span>Ending Investable Assets</span><strong>{money(last.portfolio)}</strong></div><div><span>First Unfunded Month</span><strong>{result.firstShortfall??'None Modeled'}</strong></div><div><span>Income Tax over Horizon</span><strong>{money(result.years.reduce((n,y)=>n+y.taxes,0))}</strong></div><div><span>Legacy Target Gap</span><strong>{result.legacyGap===null?'Not Set':money(result.legacyGap)}</strong></div></div>
    <div className="panel"><h3>Assets & Cash over Time</h3><ChartContainer config={config} className="h-[280px] w-full"><AreaChart data={result.years}><CartesianGrid vertical={false}/><XAxis dataKey="year"/><YAxis tickFormatter={compact}/><ChartTooltip content={<ChartTooltipContent/>}/><Legend/><Area name="Investable Portfolio (Includes Cash)" dataKey="portfolio" type="monotone" stroke="#2f7df4" fill="#2f7df4" fillOpacity={0.14}/><Area name="Cash Reserves" dataKey="cash" type="monotone" stroke="#11a68a" fill="#11a68a" fillOpacity={0.12}/></AreaChart></ChartContainer></div>
    <div className="panel budget-flow"><div className="budget-toolbar"><label className="budget-field"><span>Cash-Flow Year</span><select aria-label="Cash-Flow Year" value={year} onChange={e=>setSelectedYear(e.target.value)}>{result.years.map(y=><option key={y.year}>{y.year}</option>)}</select></label><label className="budget-check"><input type="checkbox" checked={split} onChange={e=>setSplit(e.target.checked)}/> Split Pay, Pension & Social Security</label></div><p className="field-help">Planned cash flow, not observed transactions. December includes modeled annual income-tax settlement or refund. Transfers and asset withdrawals are shown separately in the ledger; they are not income.</p><ChartContainer config={config} className="h-[280px] w-full"><ComposedChart data={series}><CartesianGrid vertical={false}/><XAxis dataKey="month" tickFormatter={v=>String(v).slice(5)}/><YAxis tickFormatter={compact}/><ChartTooltip content={<ChartTooltipContent/>}/><Legend/>{split?<><Bar dataKey="pay" name="Take-Home Pay" stackId="income" fill="#11a68a"/><Bar dataKey="pension" name="Pension" stackId="income" fill="#2f7df4"/><Bar dataKey="socialSecurity" name="Social Security" stackId="income" fill="#8567e8"/><Bar dataKey="eventIncome" name="Cash Events" stackId="income" fill="#e8a82b"/><Bar dataKey="cashInterest" name="Cash Interest" stackId="income" fill="#6b8e23"/></>:<Bar dataKey="income" name="Cash Income" fill="#11a68a"/>}<Bar dataKey="outflow" name="Funded Spending & Settlement" fill="#d66b36"/><Line dataKey="net" name="Income Less Outflows (Including Refund)" stroke="#8567e8" dot={false}/></ComposedChart></ChartContainer>
    <div className="monthly-table-wrap"><table className="monthly-table"><caption>Monthly Ledger — {year}</caption><thead><tr><th>Month</th><th>Cash Income</th><th>Spending</th><th>Settlement / Refund</th><th>Asset Draws</th><th>Savings Funded</th><th>Unfunded</th><th>Cash at End</th></tr></thead><tbody>{series.map(r=><tr key={r.month}><th>{r.month}</th><td data-label="Cash Income">{money(r.income)}</td><td data-label="Spending">{money(r.spending)}</td><td data-label="Settlement / Refund">{money(r.taxSettlement-r.taxRefund)}</td><td data-label="Asset Draws">{money(r.withdrawals+r.rmd)}</td><td data-label="Savings Funded">{money(r.savingsFunded+r.payrollSavings+r.employerSavings)}</td><td data-label="Unfunded">{money(r.unfundedSpending+r.unfundedTax)}</td><td data-label="Cash at End">{money(r.cash)}</td></tr>)}</tbody></table></div>
    <details><summary>Coverage, Guardrails & Reconciliation</summary>{rows.map(r=><div className="budget-calendar-row" key={r.month}><span>{r.month}<small>Essential {money(r.essential)} · Housing {money(r.housing)} · Healthcare {money(r.healthcare)}<br/>Debt Principal {money(r.debtPrincipal)} · Interest {money(r.debtInterest)}<br/>Discretionary Cut {money(r.discretionaryReduction)} · Unmet Savings {money(r.savingsUnfunded)}</small></span><span>Cash Target {money(r.cashTarget)}<br/>Reserve Gap {money(r.bufferGap)}<br/>Balance Residual {r.conservationResidual.toFixed(6)}</span></div>)}</details></div></>}
  </section>;
}

function EventsEditor({events,onChange}:{events:PlanEvent[];onChange:(events:PlanEvent[])=>void}) {
  const update=(id:string,patch:Partial<PlanEvent>)=>onChange(events.map(e=>e.id===id?{...e,...patch}:e));
  return <section className="panel budget-flow"><h2>Dated Life Events</h2><p>One-time expenses or confirmed cash receipts. Cash inheritance or gifts need an entered taxable portion, including zero. Do not enter an inherited IRA, a home sale, or an asset transfer here; those need their own asset/basis rules.</p>{events.map(e=><div className="budget-card" key={e.id}><div className="budget-fields"><label className="budget-field"><span>Event Label</span><Input value={e.name} onChange={v=>update(e.id,{name:v.target.value})}/></label><label className="budget-field"><span>Event Month</span><Input aria-label="Event Month" type="month" value={e.month} onChange={v=>update(e.id,{month:v.target.value})}/></label><label className="budget-field"><span>Event Type</span><select value={e.kind} onChange={v=>update(e.id,{kind:v.target.value as PlanEvent['kind']})}><option value="expense">One-Time Expense</option><option value="cashReceipt">Confirmed Cash Receipt</option></select></label><Amount label="Event Amount" value={e.amount} onChange={amount=>update(e.id,{amount})}/>{e.kind==='cashReceipt'&&<><Amount label="Ordinary Taxable Portion" value={e.taxableAmount} onChange={taxableAmount=>update(e.id,{taxableAmount})}/><label className="budget-check"><input type="checkbox" checked={e.confirmedCashTreatment} onChange={v=>update(e.id,{confirmedCashTreatment:v.target.checked})}/> I have confirmed the cash and tax treatment.</label></>}</div><Button variant="ghost" onClick={()=>onChange(events.filter(v=>v.id!==e.id))}>Remove Event</Button></div>)}<Button variant="outline" onClick={()=>onChange([...events,{id:crypto.randomUUID(),name:'',month:'',kind:'expense',amount:null,taxableAmount:null,confirmedCashTreatment:false}])}>Add Life Event</Button></section>;
}

export function ScenarioLaboratory({plan,onChange}:{plan:PlannerData;onChange:(plan:PlannerData)=>void}) {
  const lab=plan.laboratory??structuredClone(EMPTY_LAB);
  const [selected,setSelected]=useState('');
  const [rebase,setRebase]=useState('');
  const baseline=useMemo(()=>projectMonthly(plan),[plan]);
  const compared=useMemo(()=>comparison(plan,lab.scenarios.filter(s=>s.id===selected)),[plan,selected]);
  const scenario=lab.scenarios.find(s=>s.id===selected);
  const write=(patch:Partial<Laboratory>)=>onChange({...plan,laboratory:{...lab,...patch}});
  const setSetting=<K extends keyof MonthlySettings>(key:K,value:MonthlySettings[K])=>write({settings:{...lab.settings,[key]:value}});
  const edit=(patch:Partial<SavedScenario>)=>{if(scenario)write({scenarios:lab.scenarios.map(s=>s.id===scenario.id?{...s,...patch}:s)});};
  const override=(patch:SavedScenario['overrides'])=>{if(scenario)edit({overrides:{...scenario.overrides,...patch}});};
  return <div className="budget-flow"><div className="section-heading"><h1>Scenario Laboratory</h1><p>Understand the month, then compare the decision. Everything stays in your local plan.</p></div>
    <section className="panel budget-flow"><h2>Projection Scope</h2><p>This monthly model uses your linked budgets, payroll breakdown, accounts, entered benefits and dated costs. Confirm the January 1 balance year and retirement months in either Budget page. Existing annual account contributions are replaced by explicitly funded payroll/savings transfers here.</p><label className="budget-check"><input type="checkbox" checked={lab.settings.enabled} onChange={e=>setSetting('enabled',e.target.checked)}/> Use Monthly Results in Plan Summary and PDF</label><details><summary>Calculation Conventions & Limits</summary><p>Pay and scheduled bills occur before month-end returns. Benefits use entered amounts and age-based January starts. Undated bills use monthly averages. Cash earns its separate rate. Income tax settles in December using the shared 2026 federal, Social Security, capital-gains and NIIT modules; future ordinary/gains bands are planning-indexed. State tax remains your effective-rate estimate. Withholding is reconciled but quarterly estimated-payment rules and penalties are not modeled.</p><p>RMDs, QCDs and confirmed conversions occur in December. Only confirmed fully pretax eligible sources can convert; each converted lot is unavailable for five tax years in this conservative model. Roth draws also require age 60 and a confirmed qualified-distribution year. HSA assets remain reserved; automatic qualified medical reimbursements are not modeled here. Unfunded debt service invalidates the assumption that the scheduled debt balance is achieved. ACA/IRMAA worksheets remain fixed-law sensitivities, not automatic monthly premium forecasts.</p><p>Sources: <a href="https://www.irs.gov/publications/p590b" target="_blank" rel="noreferrer">IRS Publication 590-B (2025)</a>, <a href="https://www.irs.gov/publications/p505" target="_blank" rel="noreferrer">Publication 505 (2026)</a>, and the effective-dated tax modules under Taxes & Withdrawals. Verified September 7, 2026. No plan values are sent when opening these generic sources.</p></details></section>
    <details className="panel budget-flow"><summary>Confirm Account Access for Conversions & Roth Withdrawals</summary><p>Use only after checking your account's actual tax treatment. Do not confirm inherited accounts, nondeductible IRA basis, or unverified workplace rollover eligibility. The qualified Roth year must reflect both the holding period and applicable distribution rules.</p>{plan.accounts.filter(a=>['traditional','roth'].includes(a.kind)).map(a=><div className="budget-calendar-row" key={a.id}><span>{a.name||a.kind}</span>{a.kind==='traditional'?<label className="budget-check"><input type="checkbox" checked={a.conversionEligiblePretax??false} onChange={e=>onChange({...plan,accounts:plan.accounts.map(v=>v.id===a.id?{...v,conversionEligiblePretax:e.target.checked}:v)})}/> Confirmed Eligible, Fully Pretax Conversion Source</label>:<label className="budget-field"><span>Qualified Roth from Year</span><Input type="number" value={a.rothQualifiedFromYear||''} onChange={e=>onChange({...plan,accounts:plan.accounts.map(v=>v.id===a.id?{...v,rothQualifiedFromYear:e.target.value===''?undefined:+e.target.value}:v)})}/></label>}</div>)}</details>
    <section className="panel budget-flow"><h2>Cash Coverage & Spending Guardrails</h2><p>Your target covers essential everyday bills, housing, entered healthcare, timed costs and debt service, less your entered dependable monthly income. Extra reserve is separate; enter only obligations not already covered. Coverage duration is your choice, not a universal recommendation.</p><div className="budget-fields">{(['cashCoverageMonths','dependableIncomeMonthly','reserveExtra','guardrailFloor','discretionaryCutPercent','legacyTarget'] as const).map(key=>key==='cashCoverageMonths'?<label key={key} className="budget-field"><span>Coverage Duration / Months</span><Input aria-label="Coverage Duration / Months" type="number" min="0" value={lab.settings[key]??''} onChange={e=>setSetting(key,e.target.value===''?null:+e.target.value)}/></label>:<Amount key={key} percent={key==='discretionaryCutPercent'} label={{dependableIncomeMonthly:'Dependable Income / Month',reserveExtra:'Additional Reserve',guardrailFloor:'Portfolio Floor in Today’s Dollars',discretionaryCutPercent:'Discretionary Reduction / %',legacyTarget:'Ending Legacy Target'}[key]} value={lab.settings[key]} onChange={v=>setSetting(key,v)}/>)}</div><label className="budget-check"><input type="checkbox" checked={lab.settings.refillCash} onChange={e=>setSetting('refillCash',e.target.checked)}/> Refill cash toward the target from available investments</label><label className="budget-check"><input type="checkbox" checked={lab.settings.legacyRealDollars} onChange={e=>setSetting('legacyRealDollars',e.target.checked)}/> Legacy target is in today's dollars</label><p className="field-help">Refilling can realize gains or taxable withdrawals; the tax calculation includes them. It does not force cash back into investments. A guardrail cuts only discretionary everyday costs while assets are below your inflation-adjusted floor; spending restores once assets recover. Every cut is reported. The target is a coverage estimate, not an earmarked account or a guarantee against irregular bills.</p></section>
    <EventsEditor events={lab.events} onChange={events=>write({events})}/>
    <section className="panel budget-flow"><h2>Saved Scenarios</h2><p>Each scenario preserves a local baseline snapshot plus explicit changes. Updating your plan marks older scenarios stale; you decide whether to rebase them. Comparisons use the same deterministic return path unless you explicitly change a year.</p><div className="budget-toolbar"><Button onClick={()=>{const id=crypto.randomUUID();write({scenarios:[...lab.scenarios,{id,name:'',baseline:baselineSnapshot(plan),overrides:{}}]});setSelected(id);}}>Create Scenario</Button><label className="budget-field"><span>Selected Scenario</span><select aria-label="Selected Scenario" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Current Baseline</option>{lab.scenarios.map((s,i)=><option key={s.id} value={s.id}>{s.name||`Scenario ${i+1}`}{scenarioIsStale(plan,s)?' — Baseline Changed':''}</option>)}</select></label></div>
    {scenario&&<><div className="budget-fields"><label className="budget-field"><span>Scenario Name (Optional)</span><Input aria-label="Scenario Name" value={scenario.name} onChange={e=>edit({name:e.target.value})}/></label><label className="budget-field"><span>Your Retirement Month Override</span><Input type="month" value={scenario.overrides.retirementMonthYou??''} onChange={e=>override({retirementMonthYou:e.target.value||undefined})}/></label>{plan.household.maritalStatus==='married'&&<label className="budget-field"><span>Partner Retirement Month Override</span><Input type="month" value={scenario.overrides.retirementMonthPartner??''} onChange={e=>override({retirementMonthPartner:e.target.value||undefined})}/></label>}<Amount label="Everyday Spending Change / %" percent value={scenario.overrides.spendingChangePercent??null} onChange={v=>override({spendingChangePercent:v??undefined})}/><Amount label="Scenario Inflation / %" percent value={scenario.overrides.inflation??null} onChange={v=>override({inflation:v??undefined})}/><label className="budget-field"><span>Plan Through Age Override</span><Input type="number" min="1" max="120" value={scenario.overrides.planToAge??''} onChange={e=>override({planToAge:e.target.value===''?undefined:+e.target.value})}/></label></div>
    <details><summary>Explicit Return Stress Years</summary><p>Enter hypothetical annual investment returns. These are not historical replay or predictions. Cash keeps its own entered rate. The remaining years retain the baseline assumptions.</p>{(scenario.overrides.returnYears??[]).map((r,i)=><div className="budget-fields" key={i}><label className="budget-field"><span>Stress Year</span><Input type="number" value={r.year||''} onChange={e=>override({returnYears:scenario.overrides.returnYears!.map((v,j)=>j===i?{...v,year:e.target.value===''?null:+e.target.value}:v)})}/></label><Amount percent label="Annual Investment Return / %" value={Number.isFinite(r.rate)?r.rate:null} onChange={v=>override({returnYears:scenario.overrides.returnYears!.map((w,j)=>j===i?{...w,rate:v}:w)})}/><Button variant="ghost" onClick={()=>override({returnYears:scenario.overrides.returnYears!.filter((_,j)=>j!==i)})}>Remove Stress Year</Button></div>)}<Button variant="outline" onClick={()=>override({returnYears:[...(scenario.overrides.returnYears??[]),{year:null,rate:null}]})}>Add Stress Year</Button></details>
    {scenarioIsStale(plan,scenario)&&<div className="budget-card"><strong>Baseline Changed</strong><p>{scenarioChanges(plan,scenario).join(', ')}. Displayed deltas still compare against this scenario's own saved baseline.</p><Button variant="outline" onClick={()=>setRebase(scenario.id)}>Review Rebase</Button>{rebase===scenario.id&&<><p>Replace this saved baseline with the current plan and retain the explicit overrides shown above?</p><Button onClick={()=>{edit({baseline:baselineSnapshot(plan)});setRebase('');}}>Apply Rebase</Button></>}</div>}
    <div className="budget-actions"><Button variant="outline" onClick={()=>{const id=crypto.randomUUID();write({scenarios:[...lab.scenarios,{...structuredClone(scenario),id,name:scenario.name?`${scenario.name} Copy`:''}]});setSelected(id);}}>Duplicate Scenario</Button><Button variant="outline" onClick={()=>edit({overrides:{}})}>Reset Overrides</Button><Button variant="ghost" onClick={()=>{write({scenarios:lab.scenarios.filter(s=>s.id!==scenario.id)});setSelected('');}}>Delete Scenario</Button></div>
    {compared.scenarios.map(c=><div key={c.scenario.id}><div className="budget-metrics"><div><span>Ending Portfolio Change vs Saved Baseline</span><strong>{c.comparable?money(c.deltaPortfolio):'Needs Review'}</strong></div><div><span>Full-Horizon Tax Change</span><strong>{c.comparable?money(c.deltaTax):'Needs Review'}</strong></div></div><MonthlyResults result={c.result} title="Selected Scenario Results"/></div>)}</>}
    </section><ScenarioComparison plan={plan}/><MonthlyResults result={baseline}/>
    <details className="panel"><summary>Remaining Specialized Comparisons</summary><p>Automatic Social Security claiming/survivor transitions, move-state tax rules, home-sale exclusions, inherited retirement accounts, and a fully funded mortgage payoff versus investing comparison remain explicit dependencies. Do not simulate them by moving unchanged benefits, adding gross sale proceeds, or assuming zero tax. This laboratory currently supports budget/timing changes, user-entered inflation/return stresses, cash coverage, spending guardrails, confirmed cash events, and a legacy target.</p></details>
  </div>;
}

export function MonthlyPrintReport({result,plan}:{result:MonthlyResult;plan?:PlannerData}) {
  const max=Math.max(1,...result.years.map(y=>y.portfolio));
  const points=result.years.map((y,i)=>`${40+i*620/Math.max(1,result.years.length-1)},${240-y.portfolio/max*210}`).join(' ');
  return <section className="monthly-print"><h2>Monthly Planning Results</h2>{result.issues.map(i=><p key={i}>{i}</p>)}{result.years.length>0&&<><p>First unfunded month: {result.firstShortfall??'None Modeled'}. Figures are nominal; tax rules and source limitations are those shown in Scenario Laboratory.</p><svg viewBox="0 0 700 280" role="img" aria-label="Monthly Engine Portfolio Projection"><line x1="40" y1="240" x2="660" y2="240" stroke="#64748b"/><polyline points={points} fill="none" stroke="#2f7df4" strokeWidth="3"/><text x="40" y="20">{money(max)}</text><text x="40" y="268">{result.years[0].year}</text><text x="620" y="268">{result.years.at(-1)!.year}</text></svg><table><thead><tr><th>Year</th><th>Income</th><th>Spending</th><th>Income Tax</th><th>Unfunded</th><th>Portfolio</th></tr></thead><tbody>{result.years.map(y=><tr key={y.year}><td>{y.year}</td><td>{money(y.income)}</td><td>{money(y.spending)}</td><td>{money(y.taxes)}</td><td>{money(y.unfunded)}</td><td>{money(y.portfolio)}</td></tr>)}</tbody></table>{plan&&(plan.laboratory?.scenarios.length??0)>0&&<><h2>Saved Scenario Comparisons</h2>{comparison(plan,plan.laboratory!.scenarios.slice(0,3)).scenarios.map((c,i)=><p key={c.scenario.id}><strong>{c.scenario.name||`Scenario ${i+1}`}</strong>: {c.comparable?`Ending portfolio change ${money(c.deltaPortfolio)}; full-horizon tax change ${money(c.deltaTax)}.`:'Inputs or rule review required.'} {c.stale?'Compared with its earlier saved baseline; current baseline has changed.':'Compared with the current baseline.'} Changes: {Object.keys(c.scenario.overrides).join(', ')||'None'}.</p>)}</>}</>}</section>;
}
