/* Public fictional sample only; shared release checks for Chromium and WebKit. */
const assert=require('node:assert/strict');
const path=require('node:path');
const fs=require('node:fs');
module.exports=async function checkEnrollment({page,navigate,noOverflow,name,width,out}){
  await navigate('Open Enrollment');
  await page.getByRole('heading',{name:'Compare the Complete Picture',exact:true}).waitFor();
  assert.equal(await page.locator('main .oe-result').count(),3,'All sample health options produce complete results');
  assert.equal(await page.locator('main .oe-person-results progress').count(),2,'Each family member has individual limit tracking');
  await page.locator('.oe-person > summary').first().click();
  await page.getByLabel('General Medical / Year',{exact:true}).first().fill('10000');
  assert.equal(await page.locator('main .oe-result').count(),3);
  await page.locator('.oe-person > summary').first().click();
  const firstOption=page.locator('main .oe-option').first();
  await firstOption.getByText('Visits & Prescription Coverage',{exact:true}).click();
  await firstOption.locator('.oe-care > summary').first().click();
  await firstOption.getByLabel('Counts Toward Combined OOP Max?',{exact:true}).first().selectOption('unknown');
  assert.equal(await page.locator('main .oe-result').count(),0,'Unknown Rx rules suppress comparison');
  const missingRx=firstOption.getByLabel('Counts Toward Combined OOP Max?',{exact:true}).first();
  assert.equal(await missingRx.getAttribute('aria-invalid'),'true');
  assert.ok(await page.getByText('Can’t compare until missing information is entered.',{exact:true}).isVisible());
  assert.equal(await page.locator('main .oe-issues').count(),0,'No duplicate warning wall');
  await firstOption.getByLabel('Counts Toward Combined OOP Max?',{exact:true}).first().selectOption('yes');
  assert.equal(await page.locator('main .oe-result').count(),3);
  await noOverflow('expanded enrollment option');
  await firstOption.getByText('Visits & Prescription Coverage',{exact:true}).click();
  await page.getByLabel('Medical-Use Scenario',{exact:true}).selectOption('2');
  await page.getByText('How the Comparison Changes with Medical Use',{exact:true}).click();
  await noOverflow('enrollment charts');
  assert.ok(await page.locator('main .oe-best').count()>0,'A complete comparison identifies lowest modeled cost');
  const barRow=page.locator('main .oe-cost-bars > div').first();
  const barBox=await barRow.locator('svg').boundingBox(),captionBox=await barRow.locator('small').boundingBox();
  assert.ok(captionBox.y>=barBox.y+barBox.height-1,'Cost caption sits below its bar');
  assert.equal(await page.getByText(/Before HSA Benefits/).count(),0);
  await page.getByText('Monthly Cash Ledger',{exact:true}).click();
  await noOverflow('enrollment cash ledger');
  await page.getByText('Monthly Cash Ledger',{exact:true}).click();
  await page.getByRole('heading',{name:'Compare the Complete Picture',exact:true}).scrollIntoViewIfNeeded();
  await page.screenshot({path:path.join(out,`${name}-${width}-enrollment.png`)});
  if(width===1280){
    await page.emulateMedia({media:'print'});
    const report=page.locator('.oe-print');
    assert.ok(await report.getByRole('heading',{name:'Open Enrollment Comparison',exact:true}).isVisible());
    assert.ok(await report.locator('svg rect').evaluateAll(rs=>rs.some(r=>r.getBBox().width>0)),'Enrollment print bars have real geometry');
    assert.ok(await report.locator('svg line').evaluateAll(rs=>rs.some(r=>r.getBBox().width>0)),'Enrollment print timelines render');
    if(name==='chromium')await page.pdf({path:path.join(out,'synthetic-enrollment-report.pdf'),format:'Letter',printBackground:true});
    await page.emulateMedia({media:'screen'});
  }
  // Native month widgets are not required, including on Mobile Safari.
  await page.getByLabel('Plan Year',{exact:true}).selectOption('');
  assert.equal(await page.getByLabel('Plan Year',{exact:true}).getAttribute('aria-invalid'),'true');
  await page.getByLabel('Start Month',{exact:true}).selectOption('02');
  await page.getByLabel('Plan Year',{exact:true}).selectOption('2026');
  assert.equal(await page.getByLabel('Start Month',{exact:true}).inputValue(),'02');
  await page.getByLabel('Start Month',{exact:true}).selectOption('01');
  assert.equal(await page.locator('main .oe-result').count(),3);
  assert.equal(await page.getByRole('checkbox',{name:/I (?:verified|confirmed)/}).count(),0,'No certification checklist');
  // Federal directory and incentive flow use only public source values and fictional care.
  assert.equal(await page.locator('meta[name="google-site-verification"]').getAttribute('content'),'0c6rIGtsi0vIXaNJcUnNhDZHn7Hlev-DG2C3p_K-8GA');
  await page.getByRole('checkbox',{name:'Include Federal Employee Options',exact:true}).check();
  await page.getByLabel('Federal Employee',{exact:true}).selectOption('you');
  await page.getByLabel('Federal Home or Work ZIP',{exact:true}).fill('00000');
  assert.equal(await page.getByLabel('Federal Home or Work ZIP',{exact:true}).inputValue(),'00000','Partial ZIP entry survives controlled edits');
  await page.getByLabel('Employee Rate Category',{exact:true}).selectOption('active');
  await page.getByText('Browse Federal Options and Published Benefits',{exact:true}).click();
  await page.getByLabel('Search Federal Options',{exact:true}).fill('GEHA');
  await page.getByText('GEHA · HDHP',{exact:true}).click();
  await page.getByRole('button',{name:'Add 342',exact:true}).click();
  const review=page.locator('main .fehb-review').first();
  assert.equal(await review.getAttribute('open'),'','Missing federal fields automatically expand their option');
  assert.equal(await review.getByLabel('Per-Person OOP Max',{exact:true}).inputValue(),'','Self-only maximum is never copied into family coverage');
  assert.equal(await review.getByLabel('Per-Person OOP Max',{exact:true}).getAttribute('aria-invalid'),'true');
  assert.ok(await review.getByLabel('Per-Person OOP Max',{exact:true}).isVisible());
  assert.equal(await page.locator('main .oe-result').count(),3,'Unreviewed federal rules do not displace completed private comparisons');
  await noOverflow('federal benefit review');
  await review.getByRole('button',{name:'Remove Option 1',exact:true}).click();
  await page.getByRole('checkbox',{name:'Include Federal Employee Options',exact:true}).uncheck();
  const privateOptions=page.locator('main .oe-options > .oe-option');
  for(let i=0;i<3;i++){
    const card=privateOptions.nth(i);
    await card.getByText('Employer & Surcharge',{exact:true}).click();
    await card.getByLabel('Coverage Employer',{exact:true}).selectOption('partner');
    await card.getByText('Employer & Surcharge',{exact:true}).click();
  }
  const price=async()=>Number((await page.locator('main .oe-result .oe-price').first().textContent()).replace(/[^0-9.-]/g,''));
  const beforeWaiver=await price();
  await page.getByText('2a. Employer Incentives',{exact:true}).click();
  await page.getByRole('button',{name:'Add Your Waiver Payment',exact:true}).click();
  await page.getByLabel('Full-Year Waiver Payment',{exact:true}).fill('1200');
  await page.getByLabel('First Eligible Plan Month',{exact:true}).fill('1');
  await page.getByLabel('Last Eligible Plan Month',{exact:true}).fill('12');
  assert.equal(await price(),beforeWaiver-1200,'An entered waiver changes the displayed household cost');
  await noOverflow('employer waiver incentives');
  await page.getByRole('button',{name:'Remove Incentive',exact:true}).click();
  await page.getByRole('button',{name:'Share Employer Options',exact:true}).click();
  await noOverflow('employer export review');
  const downloadPromise=page.waitForEvent('download');
  await page.getByRole('button',{name:'Download Terms Only',exact:true}).click();
  const download=await downloadPromise,filePath=await download.path(),pkg=JSON.parse(fs.readFileSync(filePath,'utf8'));
  assert.equal(pkg.options.length,3);assert.ok(pkg.options.every(p=>!('label' in p)&&!('ownHsa' in p)&&!('rules' in p)&&!('taxRate' in p)));
  await page.getByLabel('Employer Options File',{exact:true}).setInputFiles({name:'fictional-employer-options.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(pkg))});
  await page.getByRole('region',{name:'Employer Import Review',exact:true}).waitFor();
  await noOverflow('employer import review');
  assert.equal(await page.locator('main .oe-result').count(),3,'Pending import does not overwrite current comparison');
  await page.getByRole('button',{name:'Replace Health Options',exact:true}).click();
  assert.equal(await page.locator('main .oe-person').count(),2,'Recipient people survive terms import');
  assert.equal(await page.locator('main .oe-result').count(),0,'New personal coverage must be confirmed');
  await page.getByRole('button',{name:'Term Life',exact:true}).click();
  await page.getByRole('heading',{name:'Portable Term-Life Comparison',exact:true}).waitFor();
  await noOverflow('term-only quotes');
  await page.screenshot({path:path.join(out,`${name}-${width}-term.png`)});
};
